In [2]:
!pip install ollama

Collecting ollama
  Downloading ollama-0.5.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.11/dist-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in /usr/local/lib/python3.11/dist-packages (from ollama) (2.11.7)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->ollama) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->ollama) (2025.7.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->ollama) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9->ollama) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9->ollama) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9->ollama) (0.4.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.27->ollama) (1.3.1)
Downloading ollama-0.5.1-py3-none-any.whl (13 kB)
Installing collected packages: ollama
Successfully installed ollama-0.5.1

In [3]:
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn import preprocessing
import scipy
import sympy
from sympy import *
from sympy.solvers.ode.systems import dsolve_system
from sympy import init_printing
init_printing()
from sympy import symbols, Eq, Function, dsolve
from sympy import init_printing
init_printing()
import math
from scipy.integrate import odeint
from scipy.integrate import odeint
from scipy.integrate import solve_ivp  # or nothing
import os
import random
import torch
import json
import requests
import time
import hashlib
from typing import List, Dict, Any, Tuple, Literal, Union
from tqdm import tqdm
import ast
from requests.exceptions import ConnectionError
from http.client import RemoteDisconnected
#from x_llm import llm_query
import ollama
import weakref
from google.colab import drive

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
!pwd

/content

In [6]:
DEFAULT_MODEL_PARAMS = {'top_k':1,'temperature':0.1, 'top_p':0.0001}

# CACHE_PATH = os.path.join( 'tmp', "cache_llm_respostas_ANALISES.json" )
CACHE_PATH = "/content/drive/MyDrive/codigo_python/cache_llm_respostas_ANALISES.json"
# HOST_OLLAMA = "10.10.10.106:11434"
HOST_OLLAMA = 'local'
SAVE_CACHE_INTERVAL=1
SEED = 42
DEFAULT_TIME_SLEEP = 1

def fixar_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    # torch.manual_seed(seed)

    # if torch.cuda.is_available():
    #     # torch.cuda.manual_seed(seed)
    #     # torch.cuda.manual_seed_all(seed)  # para múltiplas GPUs
    #     torch.backends.cudnn.deterministic = True
    #     torch.backends.cudnn.benchmark = False



LLMModelsType = Union[
    str,
    Tuple[str, Literal['ollama', 'openrouter']]
]

class LLMInference:
    def __init__(self, api_key: str, models: List[LLMModelsType] = [], models_params: List[Dict[str, str]] = None,
                 system_prompt: str = None,
                 structured_output_instructions: Dict[str, Any] = None,
                 use_cache: bool = True,
                 cache_interval:int = 10,
                 cache_path: str = CACHE_PATH,
                 default_model_type:Literal['ollama', 'openrouter'] = 'ollama',
                 fix_seed:int = 42,
                 host_ollama: str = HOST_OLLAMA,
                 default_time_sleep: int = DEFAULT_TIME_SLEEP):
        """
        Initialize the batch inference class using OpenAI client for OpenRouter.

        Args:
            api_key (str): Your OpenRouter API key.
            models (List[str]): List of model names to query.
            system_prompt (str): Common system prompt for all queries.
            structured_output_instructions (Dict[str, Any]): Instructions to guide the output structure.
        """

        self.models = models
        if models_params is None:
            self.models_params = [DEFAULT_MODEL_PARAMS]*len(models)
        else:
            self.models_params = models_params
        self.system_prompt = system_prompt
        self.structured_output_instructions = structured_output_instructions
        self.api_key = api_key

        if fix_seed is not None:
            fixar_seed( fix_seed )

        self.seed = fix_seed
        self.default_model_type = default_model_type
        self.use_cache = use_cache
        self.cache_interval = cache_interval
        self.cache_path = cache_path
        self.host_ollama = host_ollama
        self.cache_counter = 0
        self.default_time_sleep = default_time_sleep

        if os.path.exists(self.cache_path):
            with open(self.cache_path) as f:
                self.cache = json.load(f)
                print('cache lido', flush=True)
        else:
            self.cache = {}

        weakref.finalize(self, self._save_cache)


    def _create_messages(self, user_prompt: str) -> List[Dict[str, str]]:
        """
        Create the message payload.

        Args:
            user_prompt (str): The user-specific prompt.

        Returns:
            List[Dict[str, str]]: Messages to send to the model.
        """
        messages = []
        if self.system_prompt:
            messages.append( {"role": "system", "content": self.system_prompt} )
        messages.append({"role": "user", "content": user_prompt})
        if self.structured_output_instructions:
            messages.append( {"role": "user", "content": f"Format your output according to: {self.structured_output_instructions}"} )
        return messages

    def _query_model_raw_openrouter(self, model: str, model_params: Dict[str,Any], user_prompt: str, max_retries:int=5) -> str:
        """
        Query a single model using OpenAI client.

        Args:
            model (str): Model name.
            user_prompt (str): User-specific prompt.

        Returns:
            str: Model's output content.
        """
        # completion = self.client.chat.completions.create(
        #     model=model,
        #     messages=self._create_messages(user_prompt),
        #     top_k=1,
        #     temperature=0.1
        # )
        # return completion.choices[0].message.content

        url = "https://openrouter.ai/api/v1/chat/completions"
        headers = {
        "Authorization": f"Bearer {self.api_key}",
        "Content-Type": "application/json"
        }
        payload = {
        "model": model,
        "messages": self._create_messages(user_prompt)
        }
        payload.update(model_params)


        retry_count = 0

        while True:
            try:
                response = requests.post(url, headers=headers, json=payload, timeout = 300)
                response.raise_for_status()  # levanta erro se status >= 400
                if self.default_time_sleep > 0:
                    time.sleep(self.default_time_sleep)
                # print("Sucesso:", response.status_code)
                break  # sai do loop se a requisição for bem-sucedida

            except (ConnectionError, RemoteDisconnected) as e:
                retry_count += 1
                if retry_count > max_retries:
                    print("Max retries reached. Exiting...")
                    raise
                print("Erro de conexao:", e)
                print(f"Erro de conexão detectado ({retry_count}/{max_retries}): {e}")
                print("Aguardando 60 segundos antes de tentar novamente...", flush=True)
                time.sleep(60)

            except Exception as e:
                print("Erro inesperado:", e)
                raise
                # break  # interrompe se for outro erro que não de conexão


        # response = requests.post(url, headers=headers, json=payload, timeout = 300)
        # response.raise_for_status()  # dispara exceção se status >= 400

        return response.json()['choices'][0]['message']['content']

    def _query_ollama(self, model: str, model_params: Dict[str, Any], user_prompt: str) -> str:
        if self.host_ollama == 'local':
            client = ollama
        else:
            client = ollama.Client(host=self.host_ollama)


        if self.seed is not None and not 'seed' in model_params:
            model_params['seed'] = self.seed

        response = client.generate(
            model=model,
            prompt=user_prompt,
            stream=False,
            options=model_params,
        )

        return response['response']
    def _save_cache( self ):
        with open(self.cache_path, "w") as f:
            json.dump(self.cache, f, indent=2)

    def query_model(self, model: str, model_params: Dict[str, Any], user_prompt: str, model_type:Literal['ollama', 'openrouter'] = None, max_retries:int=5 ) -> str:
        key = hashlib.md5(user_prompt.encode()+model.encode()+str(model_params).encode()).hexdigest()
        if key in self.cache:
            print( 'USed from cache.', flush=True)
            return self.cache[key]
        try:
            # response_TXT = call_ollama(MODEL, prompt)


            if model_type is None:
                model_type = self.default_model_type
            if model_type == 'ollama':
                response_TXT =  self._query_ollama(model, model_params, user_prompt)
            elif model_type == 'openrouter':
                continua = True
                while continua:
                    try:
                        response_TXT  = self._query_model_raw_openrouter(model, model_params, user_prompt, max_retries=max_retries)
                        continua = False
                    except requests.exceptions.HTTPError as e:
                        if e.response is not None and e.response.status_code == 429:
                            self._save_cache()
                            print("Erro 429: too many requests / rate limit exceeded. Sleeping...")
                            time.sleep( 60 )
                        else:
                            raise
            else:
                raise ValueError(f"Unsupported model type: {model_type}. Use 'ollama' or 'openrouter'.")
        except Exception as e:
            self._save_cache()
            raise

        reply = response_TXT.strip()
        self.cache[key] = reply
        self.cache_counter+=1
        if self.cache_counter % SAVE_CACHE_INTERVAL == 0:
            self._save_cache()
            print('Cache saved to disk.', flush=True)
        # print(f"Cache hit: {self.cache_counter} - {key}", flush=True)
        return reply

    def generate_outputs(self, dataset: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
        """
        Generate outputs for each model given a labeled dataset.

        Args:
            dataset (List[Dict[str, Any]]): List of data points with 'text' and 'label'.

        Returns:
            Dict[str, List[Dict[str, Any]]]: Outputs organized by model name.
        """
        all_outputs = {model: [] for model in self.models}

        for data_point in tqdm(dataset):
            user_prompt = f"Text: {data_point['text']}\nLabel: {data_point['label']}"

            for model, model_params in zip(self.models, self.models_params):
                try:
                    print(f"Querying model {model}...")
                    output = self.query_model(model, model_params, user_prompt)
                    all_outputs[model].append({
                        "input": data_point,
                        "output": output
                    })
                    time.sleep(1)  # Sleep between requests to be polite
                except Exception as e:
                    print(f"Error querying model {model}: {e}")
                    all_outputs[model].append({
                        "input": data_point,
                        "output": {"error": str(e)}
                    })

        return all_outputs

In [7]:
DEFAULT_MODEL_PARAMS = {'top_k':1,'temperature':0.1, 'top_p':0.0001}

#CACHE_PATH = "cache_llm_respostas_ANALISES.json"
CACHE_PATH = "/content/drive/MyDrive/codigo_python/cache_llm_respostas_ANALISES.json"
# HOST_OLLAMA = "10.10.10.106:11434"
MY_KEY = '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'

my_llm = LLMInference(
            api_key = MY_KEY,
            use_cache = True,
            cache_interval = 10,
            cache_path = CACHE_PATH,
            default_model_type = 'openrouter', # 'ollama' ou 'openrouter'
            fix_seed = 42,
            host_ollama = 'local',
            default_time_sleep = 1
        )

cache lido

In [10]:
df=pd.read_csv('/content/math_ODEsdataset_csv.txt')
df.head(5)

,Index,Question,Proposed Solution,Answer
0,0,A population of protozoa grows at a constant r...,"We have dP/dt = kP Therefore dP/dt = 0,7944P ...",235.0000
1,1,A tank contains 1000 L of salt water with 15 k...,Let S(t) be the amount of salt (in kilograms...,12.3000
2,2,A resistor R=10Ω and an inductor L=2H are conn...,"Using Kirchhoff's Voltage Law KVL, the sum of ...",0.0000
3,3,A 5μF capacitor is charged through a 10kΩ resi...,"In an RC charging circuit, Kirchhoff's voltag...",0.0549
4,4,An object is removed from an oven at 200°C and...,Let T(t) represent the temperature of the obje...,114.1900

In [11]:
def ODE_modelling(model, text):
    prompt = f"""[Instruction]
Assume you are Dr. LLM – an expert in Ordinary Differential Equations (ODEs), with extensive experience in formulating ODE models from natural language descriptions that can be  solved using a solver. Your primary task is to convert a given open-ended math problem into a complete Python code ready to executed. The Python code Should provide a numeric answer when executed.Choose the most appropriate solver (`solve_ivp` or `odeint`) for effectively tackling each Ordinary Differential Equation (ODE) problem.
This Python code should adhere to the following criteria:
1. Your response should be a Python Code that uses one of the following solvers appropriately: `solve_ivp` or  `odeint` based on the nature of the problem.
2. The code should be a final-state approach without displaying intermediate steps or variables.
3. The final result must be rounded to exactly 5 significant figures or 5 decimal places.
4. The response must consist solely of valid Python code, ready to execute without modification.
5. Ensure all LaTeX math expressions in the problem are interpreted and translated into correct mathematical expressions in Python..


Here comes 3  examples:

=====================================================================================================================================================================================================================================================================================================================================================================
[Example 1. A population of protozoa grows at a constant relative rate of 0.44 per individual per day.
On day zero, the population consists of five  protozoa.
Calculate the population size after 8 days?]

Here are the instruction and Python code that solves the given problem and meets the specified requirements:

<think>  **Problem Analysis**:
# Step 1: Interpret the problem.
# - The population grows at a **constant relative rate** of 0.44 per day, which implies exponential growth.
# - This gives the ODE: dP/dt = 0.44 * P, where P(t) is the population at time t (in days).
# - The initial condition is P(0) = 5 (five protozoa at day zero).
# - We need to compute P(8), the population at t = 8 days.

# Step 2: Use solve_ivp to numerically solve the ODE.
# - Define the function f(t, P) = 0.44 * P.
# - Solve over the interval [0, 8] with initial value P(0) = 5.
# - Extract and print the value at t = 8 rounded to 4 decimal places.

</think> (Output-Solution)
from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.44 * P
P0 = [5]
t_span = (0, 8)
sol = solve_ivp(model, t_span, P0, t_eval=[8])
print(round(sol.y[0][0], 4))

=============================================================================================================================================================================================================
[Example 2. A body whose temperature is 20° is placed in a medium which is kept at a constant temperature of 60°. In 5 minute, the body's temperature has risen to 30°. How long will it take for the body's temperature to increase to 40°?]

Here are the instruction and Python code that solves the given problem and meets the specified requirements:

 <think>  **Problem Analysis**:
# Step 1: Newton's Law of Cooling/Heating: dT/dt = -k(T - T_env)
# Here T_env = 60°C (constant medium temperature)
# Initial temperature T(0) = 20°C
# After 5 min, T(5) = 30°C
# Find time t when T(t) = 40°C
# Step 2:
# - Calculate k from the data at t=5
# - Define a residual function for temperature difference at time t
# - Use root finding to get t when temperature reaches 40°C


</think> (Output-Solution)
import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def residual(t):
    T_env = 60
    T0 = 20
    k = -np.log((30 - T_env) / (T0 - T_env)) / 5  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(cooling, T0, time, args=(k, T_env))
    T_t = sol[-1][0]
    return T_t - 40

sol = root_scalar(residual, bracket=(0, 50), method='bisect')

print(round(sol.root, 5))

=======================================================================================================================================================================================
[Example 3. A 6μF capacitor is charged through a 30kΩ resistor from a 48V battery. Calculate how long will
it take for the voltage across the capacitor to reach 12V ?]

Here are the instruction and Python code that solves the given problem and meets the specified requirements:

 <think>  **Problem Analysis**:
# Problem: A 6μF capacitor is charged through a 30kΩ resistor from a 48V battery.
# Goal: Find time t when the voltage across the capacitor reaches 12V.
# Physical model: RC charging circuit.
# ODE: dV/dt = (1/RC) * (V_batt - V)
# Initial condition: V(0) = 0
# Target condition: V(t) = 12
# Use solve_ivp to solve numerically and root_scalar to find exact time.

</think>(Output-Solution)

from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

R = 30000          # Resistance in ohms
C = 6e-6           # Capacitance in farads
V_batt = 48        # Battery voltage in volts
V_target = 12      # Target voltage in volts

def dVdt(t, V):
    return (1 / (R * C)) * (V_batt - V)

sol = solve_ivp(dVdt, t_span=(0, 1), y0=[0], dense_output=True, rtol=1e-9, atol=1e-12)

def voltage_difference(t):
    return sol.sol(t)[0] - V_target

result = root_scalar(voltage_difference, bracket=[0, 1], method='brentq')

print(f"(result.root:.5f)")



========================================================================================================================================================================================================
The following sentences  are forbidden:
”
This code solves the  problem for the given differential equation using 'solve_ivp' from SciPy;
This code solves the  problem for the given differential equation using ‘odeint‘ from SciPy;

Please avoid the above sentences.
========================================================================================================================================================================================================
Take it easy and have a deep breath before answering the question. This won't be a challenge for you atall.


Here comes the question:
{text}

Your response:
"""
    response = my_llm.query_model( model, DEFAULT_MODEL_PARAMS, prompt)
    print("**************", model)
    print(response)
    print("************")
    return response

In [12]:
text = df.iloc[0]['Question']
model = 'deepseek/deepseek-r1-distill-llama-70b'
ODE_modelling(model, text)

Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b
from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.7944 * P

P0 = [2]
t_span = (0, 6)
sol = solve_ivp(model, t_span, P0, t_eval=[6])

print(round(sol.y[0][0], 5))
************

'from scipy.integrate import solve_ivp\nimport numpy as np\n\ndef model(t, P):\n    return 0.7944 * P\n\nP0 = [2]\nt_span = (0, 6)\nsol = solve_ivp(model, t_span, P0, t_eval=[6])\n\nprint(round(sol.y[0][0], 5))'

In [13]:
import pandas as pd
import os
import hashlib
import json
from pathlib import Path

# Configuração do cache
# CACHE_DIR = "cache"
# CACHE_FILE = Path(CACHE_DIR) / "ode_cache.json"

# Garante que o diretório de cache existe
# os.makedirs(CACHE_DIR, exist_ok=True)

CACHE_FILE = Path('/content/drive/MyDrive/codigo_python/ode_cache.json')

# Tenta carregar o cache existente
cache = {}
if CACHE_FILE.exists():
    print( 'Cache lido dos codigos!!!' )
    try:
        with open(CACHE_FILE, 'r') as f:
            cache = json.load(f)
        print(f"Cache carregado com {len(cache)} entradas")
    except:
        print("Erro ao carregar cache, iniciando novo")

def get_cache_key(model, question):
    """Gera chave única para cache"""
    return hashlib.md5(f"{model}_{question}".encode()).hexdigest()

# Carrega o dataset
df = pd.read_csv('/content/math_ODEsdataset_csv.txt')

# Processa cada modelo
for model in [
    'deepseek/deepseek-r1-distill-llama-70b',
    'meta-llama/llama-3.3-70b-instruct',
    'google/gemini-2.5-pro',
    'google/gemma-3-27b-it',
    'openai/gpt-4.1-mini',
    'deepseek/deepseek-chat-v2.5'
]:
    responses = []
    print(f"\n{'='*50}")
    print(f"Processando modelo: {model}")
    print(f"{'='*50}")

    # Verifica se já temos respostas para este modelo
    model_col = model + '_class'
    if model_col in df.columns:
        existing_responses = df[model_col].tolist()
    else:
        existing_responses = [None] * len(df)

    for index, row in df.iterrows():
        question = str(row['Question'])
        cache_key = get_cache_key(model, question)

        # Usa resposta em cache se disponível
        if cache_key in cache:
            responses.append(cache[cache_key])
            print(f"✓ Usando cache para índice {index}")
            continue

        # Usa resposta existente se válida
        if existing_responses[index] not in [None, 'error']:
            responses.append(existing_responses[index])
            cache[cache_key] = existing_responses[index]  # Adiciona ao cache
            print(f"↻ Reutilizando resposta existente para índice {index}")
            continue

        # Processa nova resposta
        max_tries = 3
        tries = 0
        result = 'error'

        while tries < max_tries:
            try:
                rsp = ODE_modelling(model, question)
                if rsp != 'error':
                    result = rsp
                    break
            except Exception as e:
                print(f"Erro inesperado: {e}")

            tries += 1
            print(f"↻ Tentativa {tries}/{max_tries} falhou no índice {index}")

        responses.append(result)
        cache[cache_key] = result  # Atualiza cache

        # Salva cache periodicamente
        if index % 10 == 0:
            with open(CACHE_FILE, 'w') as f:
                json.dump(cache, f)
            print(f"💾 Cache salvo após índice {index}")

    df[model_col] = responses

    # Salva cache após cada modelo
    with open(CACHE_FILE, 'w') as f:
        json.dump(cache, f)
    print(f"💾 Cache salvo após processar modelo {model}")

# Garante que a pasta 'results' existe
os.makedirs('results', exist_ok=True)

# Salva o CSV final
df.to_csv('math_ODEsdataset_csv.txt_models', index=False)
print("✅ Processamento completo! Resultados salvos.")

Cache lido dos codigos!!!
Cache carregado com 1189 entradas

==================================================
Processando modelo: deepseek/deepseek-r1-distill-llama-70b
==================================================
✓ Usando cache para índice 0
✓ Usando cache para índice 1
✓ Usando cache para índice 2
✓ Usando cache para índice 3
✓ Usando cache para índice 4
✓ Usando cache para índice 5
✓ Usando cache para índice 6
✓ Usando cache para índice 7
✓ Usando cache para índice 8
✓ Usando cache para índice 9
✓ Usando cache para índice 10
✓ Usando cache para índice 11
✓ Usando cache para índice 12
✓ Usando cache para índice 13
✓ Usando cache para índice 14
✓ Usando cache para índice 15
✓ Usando cache para índice 16
✓ Usando cache para índice 17
✓ Usando cache para índice 18
✓ Usando cache para índice 19
✓ Usando cache para índice 20
✓ Usando cache para índice 21
✓ Usando cache para índice 22
✓ Usando cache para índice 23
✓ Usando cache para índice 24
✓ Usando cache para índice 25
✓ Usando cache para índice 26
✓ Usando cache para índice 27
✓ Usando cache para índice 28
✓ Usando cache para índice 29
✓ Usando cache para índice 30
✓ Usando cache para índice 31
✓ Usando cache para índice 32
✓ Usando cache para índice 33
✓ Usando cache para índice 34
✓ Usando cache para índice 35
✓ Usando cache para índice 36
✓ Usando cache para índice 37
✓ Usando cache para índice 38
✓ Usando cache para índice 39
✓ Usando cache para índice 40
✓ Usando cache para índice 41
✓ Usando cache para índice 42
✓ Usando cache para índice 43
✓ Usando cache para índice 44
✓ Usando cache para índice 45
✓ Usando cache para índice 46
✓ Usando cache para índice 47
✓ Usando cache para índice 48
✓ Usando cache para índice 49
💾 Cache salvo após processar modelo deepseek/deepseek-r1-distill-llama-70b

==================================================
Processando modelo: meta-llama/llama-3.3-70b-instruct
==================================================
✓ Usando cache para índice 0
✓ Usando cache para índice 1
✓ Usando cache para índice 2
✓ Usando cache para índice 3
✓ Usando cache para índice 4
✓ Usando cache para índice 5
✓ Usando cache para índice 6
✓ Usando cache para índice 7
✓ Usando cache para índice 8
✓ Usando cache para índice 9
✓ Usando cache para índice 10
✓ Usando cache para índice 11
✓ Usando cache para índice 12
✓ Usando cache para índice 13
✓ Usando cache para índice 14
✓ Usando cache para índice 15
✓ Usando cache para índice 16
✓ Usando cache para índice 17
✓ Usando cache para índice 18
✓ Usando cache para índice 19
✓ Usando cache para índice 20
✓ Usando cache para índice 21
✓ Usando cache para índice 22
✓ Usando cache para índice 23
✓ Usando cache para índice 24
✓ Usando cache para índice 25
✓ Usando cache para índice 26
✓ Usando cache para índice 27
✓ Usando cache para índice 28
✓ Usando cache para índice 29
✓ Usando cache para índice 30
✓ Usando cache para índice 31
✓ Usando cache para índice 32
✓ Usando cache para índice 33
✓ Usando cache para índice 34
✓ Usando cache para índice 35
✓ Usando cache para índice 36
✓ Usando cache para índice 37
✓ Usando cache para índice 38
✓ Usando cache para índice 39
✓ Usando cache para índice 40
✓ Usando cache para índice 41
✓ Usando cache para índice 42
✓ Usando cache para índice 43
✓ Usando cache para índice 44
✓ Usando cache para índice 45
✓ Usando cache para índice 46
✓ Usando cache para índice 47
✓ Usando cache para índice 48
✓ Usando cache para índice 49
💾 Cache salvo após processar modelo meta-llama/llama-3.3-70b-instruct

==================================================
Processando modelo: google/gemini-2.5-pro
==================================================
✓ Usando cache para índice 0
✓ Usando cache para índice 1
✓ Usando cache para índice 2
✓ Usando cache para índice 3
✓ Usando cache para índice 4
✓ Usando cache para índice 5
✓ Usando cache para índice 6
✓ Usando cache para índice 7
✓ Usando cache para índice 8
✓ Usando cache para índice 9
✓ Usando cache para índice 10
✓ Usando cache para índice 11
✓ Usando cache para índice 12
✓ Usando cache para índice 13
✓ Usando cache para índice 14
✓ Usando cache para índice 15
✓ Usando cache para índice 16
✓ Usando cache para índice 17
✓ Usando cache para índice 18
✓ Usando cache para índice 19
✓ Usando cache para índice 20
✓ Usando cache para índice 21
✓ Usando cache para índice 22
✓ Usando cache para índice 23
✓ Usando cache para índice 24
✓ Usando cache para índice 25
✓ Usando cache para índice 26
✓ Usando cache para índice 27
✓ Usando cache para índice 28
✓ Usando cache para índice 29
✓ Usando cache para índice 30
✓ Usando cache para índice 31
✓ Usando cache para índice 32
✓ Usando cache para índice 33
✓ Usando cache para índice 34
✓ Usando cache para índice 35
✓ Usando cache para índice 36
✓ Usando cache para índice 37
✓ Usando cache para índice 38
✓ Usando cache para índice 39
✓ Usando cache para índice 40
✓ Usando cache para índice 41
✓ Usando cache para índice 42
✓ Usando cache para índice 43
✓ Usando cache para índice 44
✓ Usando cache para índice 45
✓ Usando cache para índice 46
✓ Usando cache para índice 47
✓ Usando cache para índice 48
✓ Usando cache para índice 49
💾 Cache salvo após processar modelo google/gemini-2.5-pro

==================================================
Processando modelo: google/gemma-3-27b-it
==================================================
✓ Usando cache para índice 0
✓ Usando cache para índice 1
✓ Usando cache para índice 2
✓ Usando cache para índice 3
✓ Usando cache para índice 4
✓ Usando cache para índice 5
✓ Usando cache para índice 6
✓ Usando cache para índice 7
✓ Usando cache para índice 8
✓ Usando cache para índice 9
✓ Usando cache para índice 10
✓ Usando cache para índice 11
✓ Usando cache para índice 12
✓ Usando cache para índice 13
✓ Usando cache para índice 14
✓ Usando cache para índice 15
✓ Usando cache para índice 16
✓ Usando cache para índice 17
✓ Usando cache para índice 18
✓ Usando cache para índice 19
✓ Usando cache para índice 20
✓ Usando cache para índice 21
✓ Usando cache para índice 22
✓ Usando cache para índice 23
✓ Usando cache para índice 24
✓ Usando cache para índice 25
✓ Usando cache para índice 26
✓ Usando cache para índice 27
✓ Usando cache para índice 28
✓ Usando cache para índice 29
✓ Usando cache para índice 30
✓ Usando cache para índice 31
✓ Usando cache para índice 32
✓ Usando cache para índice 33
✓ Usando cache para índice 34
✓ Usando cache para índice 35
✓ Usando cache para índice 36
✓ Usando cache para índice 37
✓ Usando cache para índice 38
✓ Usando cache para índice 39
✓ Usando cache para índice 40
✓ Usando cache para índice 41
✓ Usando cache para índice 42
✓ Usando cache para índice 43
✓ Usando cache para índice 44
✓ Usando cache para índice 45
✓ Usando cache para índice 46
✓ Usando cache para índice 47
✓ Usando cache para índice 48
✓ Usando cache para índice 49
💾 Cache salvo após processar modelo google/gemma-3-27b-it

==================================================
Processando modelo: openai/gpt-4.1-mini
==================================================
✓ Usando cache para índice 0
✓ Usando cache para índice 1
✓ Usando cache para índice 2
✓ Usando cache para índice 3
✓ Usando cache para índice 4
✓ Usando cache para índice 5
✓ Usando cache para índice 6
✓ Usando cache para índice 7
✓ Usando cache para índice 8
✓ Usando cache para índice 9
✓ Usando cache para índice 10
✓ Usando cache para índice 11
✓ Usando cache para índice 12
✓ Usando cache para índice 13
✓ Usando cache para índice 14
✓ Usando cache para índice 15
✓ Usando cache para índice 16
✓ Usando cache para índice 17
✓ Usando cache para índice 18
✓ Usando cache para índice 19
✓ Usando cache para índice 20
✓ Usando cache para índice 21
✓ Usando cache para índice 22
✓ Usando cache para índice 23
✓ Usando cache para índice 24
✓ Usando cache para índice 25
✓ Usando cache para índice 26
✓ Usando cache para índice 27
✓ Usando cache para índice 28
✓ Usando cache para índice 29
✓ Usando cache para índice 30
✓ Usando cache para índice 31
✓ Usando cache para índice 32
✓ Usando cache para índice 33
✓ Usando cache para índice 34
✓ Usando cache para índice 35
✓ Usando cache para índice 36
✓ Usando cache para índice 37
✓ Usando cache para índice 38
✓ Usando cache para índice 39
✓ Usando cache para índice 40
✓ Usando cache para índice 41
✓ Usando cache para índice 42
✓ Usando cache para índice 43
✓ Usando cache para índice 44
✓ Usando cache para índice 45
✓ Usando cache para índice 46
✓ Usando cache para índice 47
✓ Usando cache para índice 48
✓ Usando cache para índice 49
💾 Cache salvo após processar modelo openai/gpt-4.1-mini

==================================================
Processando modelo: deepseek/deepseek-chat-v2.5
==================================================
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 0
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 0
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 0
💾 Cache salvo após índice 0
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 1
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 1
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 1
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 2
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 2
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 2
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 3
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 3
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 3
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 4
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 4
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 4
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 5
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 5
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 5
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 6
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 6
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 6
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 7
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 7
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 7
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 8
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 8
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 8
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 9
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 9
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 9
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 10
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 10
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 10
💾 Cache salvo após índice 10
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 11
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 11
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 11
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 12
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 12
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 12
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 13
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 13
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 13
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 14
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 14
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 3/3 falhou no índice 14
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 1/3 falhou no índice 15
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions
↻ Tentativa 2/3 falhou no índice 15
Erro inesperado: 404 Client Error: Not Found for url: https://openrouter.ai/api/v1/chat/completions

In [15]:
import pandas as pd
import os
import re
import sympy as sp
import numpy as np
from scipy.integrate import solve_ivp, odeint
import sys
import contextlib
from io import StringIO

# === Configurações iniciais ===
#INPUT_CSV = '/content/drive/MyDrive/codigo_python/math_ODEsdataset_results.csv'
OUTPUT_CSV = '/content/drive/MyDrive/codigo_python/math_ODEsdataset_final_results.csv'

# === Ambiente simplificado para execução ===
# Mantemos apenas as funções essenciais para resolver EDOs
DEFAULT_GLOBALS = {
    'np': np,
    'sp': sp,
    'solve_ivp': solve_ivp,
    'odeint': odeint,
    'dsolve': sp.dsolve,
    'Eq': sp.Eq,
    'Function': sp.Function,
    'Symbol': sp.Symbol,
    'sin': sp.sin,
    'cos': sp.cos,
    'exp': sp.exp,
    'log': sp.log,
    'sqrt': sp.sqrt,
    'pi': sp.pi,
    'e': sp.E
}

# === Funções auxiliares ===
def extract_code(text):
    """Remove formatação Markdown do código"""
    if not isinstance(text, str):
        return ''
    return re.sub(r'```(python)?|```', '', text).strip()

@contextlib.contextmanager
def capture_stdout():
    """Captura saída impressa durante execução"""
    buffer = StringIO()
    original_stdout = sys.stdout
    sys.stdout = buffer
    try:
        yield buffer
    finally:
        sys.stdout = original_stdout

def execute_ode_code(code_str):
    """Executa código Python para soluções de EDOs"""
    try:
        local_vars = {}

        # Execução direta sem restrições excessivas
        with capture_stdout() as stdout:
            exec(code_str, DEFAULT_GLOBALS, local_vars)
        output = stdout.getvalue().strip()

        # Tenta extrair número da saída
        if output:
            try:
                return float(output)
            except ValueError:
                pass

        # Tenta encontrar resultado em variáveis de saída
        output_vars = ['result', 'solution', 'value', 'final_value', 'answer', 'output']
        for name in output_vars:
            if name in local_vars and isinstance(local_vars[name], (int, float)):
                return float(local_vars[name])

        # Tenta encontrar o último valor numérico
        for val in local_vars.values():
            if isinstance(val, (int, float)):
                return float(val)

        return None
    except Exception as e:
        print(f"Erro na execução: {str(e)[:100]}")
        return None

# === Carregar e processar o dataset ===
def process_dataset():
    # Carregar CSV
    try:
        df = pd.read_csv('/content/math_ODEsdataset_csv.txt_models')
        print(f"Dataset carregado: {len(df)} linhas")
    except FileNotFoundError:
        print(f"Erro: Arquivo não encontrado - {INPUT_CSV}")
        return

    # Identificar colunas com códigos
    code_columns = [col for col in df.columns if col.endswith('_class')]

    if not code_columns:
        print("Nenhuma coluna de código encontrada (_class)")
        return

    print(f"Colunas de código identificadas: {', '.join(code_columns)}")

    # Processar cada coluna de código
    for col in code_columns:
        result_col = col.replace('_class', '_exec_result')
        df[result_col] = 'not_executed'

        print(f"\n{'='*50}")
        print(f"Processando coluna: {col}")
        print(f"{'='*50}")

        for idx, row in df.iterrows():
            code_raw = row[col]

            if pd.isna(code_raw):
                df.at[idx, result_col] = 'no_code'
                continue

            code_clean = extract_code(str(code_raw))

            print(f'Code executing ({col}/{idx}):', code_clean, flush=True)

            if not code_clean:
                df.at[idx, result_col] = 'empty_code'
                continue

            # Executar código
            result = execute_ode_code(code_clean)

            if result is not None:
                df.at[idx, result_col] = round(result, 4)
            else:
                df.at[idx, result_col] = 'exec_error'

            # Mostrar progresso
            if (idx + 1) % 10 == 0:
                print(f"Processadas {idx+1}/{len(df)} linhas")

    # Salvar resultados
    os.makedirs('results', exist_ok=True)
    df.to_csv(OUTPUT_CSV, index=False)
    print(f"\n✅ Resultados salvos em: {OUTPUT_CSV}")

    return df

# === Execução principal ===
if __name__ == "__main__":
    print("Iniciando execução de códigos Python do dataset...")
    result_df = process_dataset()

    if result_df is not None:
        # Mostrar resumo estatístico
        print("\nResumo estatístico:")
        for col in result_df.columns:
            if col.endswith('_exec_result'):
                success_count = result_df[col].apply(lambda x: isinstance(x, float)).sum()
                error_count = len(result_df) - success_count
                print(f"{col}: {success_count} sucessos, {error_count} erros")

    print("Processamento concluído!")

A saída de streaming foi truncada nas últimas 5000 linhas.
sol = solve_ivp(model, t_span, [A0], dense_output=True, rtol=1e-9, atol=1e-12)

def amount_difference(t):
    return sol.sol(t)[0] - 2

result = root_scalar(amount_difference, bracket=[0, 50], method='brentq')

print(f"{result.root:.5f}")
Erro na execução: name 'sol' is not defined
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/32): To solve the problem using numerical methods, we'll employ `solve_ivp` to solve the ODE and `root_scalar` to find the specific time when the temperature reaches 90 degrees.


import numpy as np
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def find_time_to_90():
    T_env = 60
    T0 = 180
    t_initial = 1
    T_initial = 120

    # Calculate the cooling constant k
    k = -np.log((T_initial - T_env) / (T0 - T_env)) / t_initial

    # Define the ODE model
    def model(t, T):
        return cooling(T, t, k, T_env)

    # Solve the ODE
    sol = solve_ivp(model, (0, 5), [T0], dense_output=True, rtol=1e-9, atol=1e-12)

    # Function to find root for T(t) = 90
    def residual(t):
        return sol.sol(t)[0] - 90

    # Find the time when temperature is 90 using root_scalar
    result = root_scalar(residual, bracket=[0, 5], method='brentq')

    return round(result.root, 5)

# Execute the function
time_to_90 = find_time_to_90()
print(f"The time to reach 90 degrees is {time_to_90} minutes.")
Erro na execução: unterminated string literal (detected at line 1) (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/33): The outdoor temperature is 50°F.


import numpy as np
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

# Define the model
def dT_dt(t, T, k, T_env):
    return -k * (T - T_env)

# Initial temperature
T_initial = 70  # °F

# Data points
t1, T1 = 5, 60
t2, T2 = 10, 55

# Solve for k and T_env using the two data points
def residual1(k, T_env):
    return T_initial - (T_initial - T_env)*np.exp(-k*t1) - T1

def residual2(k, T_env):
    return T_initial - (T_initial - T_env)*np.exp(-k*t2) - T2

# Using the analytical solution to find T_env
T_env = 50  # From the analytical solution above

# Verify by solving the ODE
sol = solve_ivp(dT_dt, (0, 10), [T_initial], args=(0.1386, T_env), dense_output=True)
t = 10
T_final = sol.sol(t)[0]

print(f"The outdoor temperature is {T_env}°F.")
Erro na execução: invalid character '°' (U+00B0) (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/34): from scipy.integrate import solve_ivp
import numpy as np

def decay_model(t, N):
    lambda_ = np.log(2) / 1500  # Decay constant
    return -lambda_ * N

# Initial condition: 100% of the substance remains at t=0
y0 = [1]

# Time span: from 0 to 4500 years
t_span = (0, 4500)

# Solve the ODE
sol = solve_ivp(decay_model, t_span, y0, t_eval=[4500])

# Extract the solution at t=4500 and convert to percentage
remaining_percentage = sol.y[0][0] * 100

# Round to 5 significant figures
print(round(remaining_percentage, 5))
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/35): To solve the population growth problem, we'll use the exponential growth model. The population grows at a rate proportional to its current size, leading to the ODE dP/dt = kP. Using the given data points, we calculate the growth rate k and then use it to find the population in 2030.


import numpy as np
from scipy.integrate import solve_ivp

# Initial population in 2010
P0 = 30000
# Population in 2020
P2020 = 35000
# Time between 2010 and 2020 in years
t_span = (0, 10)
# Time to predict (2030 is 20 years after 2010)
t_predict = 20

# Calculate growth rate k
k = np.log(P2020 / P0) / 10

def model(t, P):
    return k * P

# Solve ODE
sol = solve_ivp(model, t_span, [P0], t_eval=[t_predict])

# Extract and round the result
population_2030 = round(sol.y[0][0], 5)

print(f"The population in 2030 will be {population_2030}")
Erro na execução: unterminated string literal (detected at line 1) (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/36): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

def model(t, A):
    return -0.05 * A

A0 = 1000000
t_span = (0, 30)

sol = solve_ivp(model, t_span, [A0], dense_output=True)

def residual(t):
    return sol.sol(t)[0] - 250000

result = root_scalar(residual, bracket=[0, 30], method='brentq')

print(round(result.root, 5))
Erro na execução: name 'sol' is not defined
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/37): from scipy.integrate import solve_ivp
import numpy as np

def f1(t, v):
    return 32 - 0.1 * v

def f2(t, v):
    return 32 - 2 * v

# First phase: t=0 to t=10
sol1 = solve_ivp(f1, (0, 10), [0])
v10 = sol1.y[0][-1]

# Second phase: t=10 to t=15
sol2 = solve_ivp(f2, (10, 15), [v10])
v15 = sol2.y[0][-1]

print(round(v15, 5))
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/38): To find the continuous compounding rate that causes $100 to triple in 20 years, we model the growth using the ODE dA/dt = rA with A(0) = 100. We solve for r such that A(20) = 300.


from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

def model(t, A, r):
    return r * A

def residual(r):
    A0 = 100
    t_span = (0, 20)
    sol = solve_ivp(model, t_span, [A0], args=(r,), t_eval=[20])
    return sol.y[0][0] - 300

result = root_scalar(residual, bracket=(0, 1), method='brentq')

print(f"{result.root:.5f}")
Erro na execução: invalid syntax (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/39): from scipy.integrate import odeint
import numpy as np

k = np.log(1.5) / 900  # Calculated from the given condition
y0 = 0
t = np.linspace(0, 180, 100)  # Time points from 0 to 180 minutes

def model(y, t, k):
    return k * (10 - y) * (20 - y)

sol = odeint(model, y0, t, args=(k,))
y_at_180 = sol[-1][0]

print(round(y_at_180,5))
Processadas 40/50 linhas
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/40): from scipy.integrate import solve_ivp
import numpy as np

def model(t, i):
    return 24 - 20 * i

i0 = [0]
t_span = (0, 2)
sol = solve_ivp(model, t_span, i0, t_eval=[2])
print(round(sol.y[0][0], 5))
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/41): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    k = np.log(2/3)/10  # Calculate the decay rate constant
    return -k * P

P0 = 60000  # Initial population in 2010
t_span = (0, 20)  # Time span from 2010 to 2030 (20 years)
sol = solve_ivp(model, t_span, [P0], t_eval=[20])

print(round(sol.y[0][0], 5))
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/42): To solve the problem of determining the percentage of carbon dioxide in the room after 3 minutes, we model the situation using a first-order linear ordinary differential equation. The equation accounts for the inflow and outflow rates of CO2, and we solve it numerically using `solve_ivp`.


from scipy.integrate import solve_ivp
import numpy as np

# Define the model
def model(t, Q):
    return 2.5 - 0.5 * Q

# Initial condition
Q0 = 15  # Amount of CO2 in cubic feet

# Time span
t_span = (0, 3)

# Solve ODE
sol = solve_ivp(model, t_span, [Q0], t_eval=[3])

# Calculate percentage
percentage = sol.y[0][0] / 100

# Round to 5 decimal places
rounded_percentage = round(percentage, 5)

print(f"{rounded_percentage:.5f}")
Erro na execução: invalid syntax (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/43): To solve the problem of finding the velocity of a falling body after 10 seconds with air resistance, we model the situation using an ordinary differential equation (ODE). The ODE is derived from Newton's second law, considering both gravitational force and air resistance. We then use Python's `solve_ivp` to numerically solve the ODE and find the velocity at the specified time.


from scipy.integrate import solve_ivp
import numpy as np

def velocity_model(t, v):
    return 32 - 8 * v

v0 = [0]
t_span = (0, 10)
sol = solve_ivp(velocity_model, t_span, v0, t_eval=[10])
print(round(sol.y[0][0], 5))
Erro na execução: invalid syntax (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/44): To solve the problem of determining how long it takes for a sponge to lose 95% of its moisture content, we model the situation using an exponential decay ODE. The solution involves numerically solving the ODE and finding the specific time when the moisture content reaches 5% of the initial amount.


from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

def drying_model(t, M, k):
    return -k * M

# Initial moisture content (arbitrary value since it cancels out)
M0 = 1.0

# Determine the rate constant k using the half-life information
half_life = 30  # minutes
k = np.log(2) / half_life

# Define the time span for the solution
t_span = (0, 140)  # Extended beyond expected to ensure coverage

# Solve the ODE
sol = solve_ivp(drying_model, t_span, [M0], args=(k,), dense_output=True)

# Function to find when moisture is 5% of initial
def moisture_difference(t):
    return sol.sol(t)[0] - 0.05

# Find the root
result = root_scalar(moisture_difference, bracket=[0, 140], method='brentq')

# Print the result rounded to five significant figures
print(f"{result.root:.5f}")
Erro na execução: invalid syntax (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/45): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

R = 15000  # Resistance in ohms
C = 3e-6    # Capacitance in microfarads
V_batt = 24  # Battery voltage in volts
V_target = 6  # Target voltage in volts

def dVdt(t, V):
    return (V_batt - V) / (R * C)

sol = solve_ivp(dVdt, t_span=(0, 1), y0=[0], dense_output=True)

def voltage_difference(t):
    return sol.sol(t)[0] - V_target

result = root_scalar(voltage_difference, bracket=[0, 1], method='brentq')

print(f"{result.root:.5f}")
Erro na execução: name 'V_batt' is not defined
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/46): To solve the problem of finding the velocity of the block after 4 seconds, we model the motion using the equation of motion derived from Newton's second law. The block experiences a constant acceleration down the incline, which allows us to set up a simple ordinary differential equation (ODE). We then use `solve_ivp` from SciPy to solve this ODE and find the velocity at the specified time.


from scipy.integrate import solve_ivp
import numpy as np

# Constants
g = 32.0  # ft/s²
theta = 30.0 * np.pi / 180.0  # Convert degrees to radians
mu = 0.4
mass = 1.0  # Mass cancels out in the acceleration calculation

# Calculate acceleration
a = g * (np.sin(theta) - mu * np.cos(theta))

# Define the model
def model(t, v):
    return a

# Initial condition
v0 = [0.0]

# Time span
t_span = (0.0, 4.0)

# Solve ODE
sol = solve_ivp(model, t_span, v0, t_eval=[4.0])

# Extract the result and round to 5 significant figures
velocity = sol.y[0][0]
rounded_velocity = round(velocity, 5 - len(str(int(velocity)))) if int(velocity) != 0 else round(velocity, 5)

print(f"The velocity after 4 seconds is {rounded_velocity} ft/s.")
Erro na execução: unterminated string literal (detected at line 1) (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/47): from scipy.integrate import solve_ivp
import numpy as np

def model(t, v):
    return (4/3) - (7/60)*v

y0 = [18]
t_span = (0, 30)
sol = solve_ivp(model, t_span, y0, t_eval=[30])
print(round(sol.y[0][0], 5))
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/48): from scipy.integrate import solve_ivp
import numpy as np

def velocity_model(t, v):
    return 5 - v

v0 = [0]
t_span = (0, 5)
sol = solve_ivp(velocity_model, t_span, v0, t_eval=[5])
print(round(sol.y[0][0], 5))
Code executing (deepseek/deepseek-r1-distill-llama-70b_class/49): from scipy.integrate import solve_ivp
import numpy as np

def model(t, N):
    return -0.10 * N

N0 = 15000000
t_span = (0, 5)
sol = solve_ivp(model, t_span, [N0], t_eval=[5])
print(round(sol.y[0][0], 5))
Processadas 50/50 linhas

==================================================
Processando coluna: meta-llama/llama-3.3-70b-instruct_class
==================================================
Code executing (meta-llama/llama-3.3-70b-instruct_class/0): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.7944 * P

P0 = [2]
t_span = (0, 6)
sol = solve_ivp(model, t_span, P0, t_eval=[6])
print(round(sol.y[0][0], 5))
Code executing (meta-llama/llama-3.3-70b-instruct_class/1): from scipy.integrate import odeint
import numpy as np

def model(salt, t, rate_in, rate_out, volume):
    return -rate_out * salt / volume

rate_in = 0  # kg/min (no salt entering)
rate_out = 10  # L/min
volume = 1000  # L
initial_salt = 15  # kg
time = np.linspace(0, 20, 100)

sol = odeint(model, initial_salt, time, args=(rate_in, rate_out, volume))

print(round(sol[-1][0], 5))
Code executing (meta-llama/llama-3.3-70b-instruct_class/2): import numpy as np
from scipy.integrate import odeint

# Constants
R = 10  # Resistance in ohms
L = 2   # Inductance in henries
V = 20  # Voltage in volts

# ODE: dI/dt = (1/L) * (V - R*I)
# Initial condition: I(0) = 0 (since the circuit is switched on at t=0)

def dIdt(I, t, R, L, V):
    return (1 / L) * (V - R * I)

# Since the current at t=0 is the initial condition and the circuit is just switched on,
# the initial current I(0) can be directly calculated using the formula for the current
# in an RL circuit at time t=0, which is I(0) = 0 because the inductor opposes any
# change in current and at t=0, the current is zero.

I0 = 0

print(round(I0, 5))
Code executing (meta-llama/llama-3.3-70b-instruct_class/3): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

R = 10000          # Resistance in ohms
C = 5e-6           # Capacitance in farads
V_batt = 12        # Battery voltage in volts
V_target = 8       # Target voltage in volts

def dVdt(t, V):
    return (1 / (R * C)) * (V_batt - V)

sol = solve_ivp(dVdt, t_span=(0, 1), y0=[0], dense_output=True, rtol=1e-9, atol=1e-12)

def voltage_difference(t):
    return sol.sol(t)[0] - V_target

result = root_scalar(voltage_difference, bracket=[0, 1], method='brentq')

print(f"{result.root:.5f}")
Erro na execução: name 'R' is not defined
Code executing (meta-llama/llama-3.3-70b-instruct_class/4): import numpy as np
from scipy.integrate import odeint

def cooling(T, t, k, T_room):
    return -k * (T - T_room)

T_room = 25
T0 = 200
t_data = 10
T_data = 150

k = -np.log((T_data - T_room) / (T0 - T_room)) / t_data

time = np.linspace(0, 20, 100)
sol = odeint(cooling, T0, time, args=(k, T_room))

T_20 = sol[-1][0]

print(round(T_20, 5))
Code executing (meta-llama/llama-3.3-70b-instruct_class/5): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def population_decrease(P, t, k):
    return -k * P

def residual(t):
    P0 = 10000
    P_at_3_years = 8000
    k = -np.log(P_at_3_years / P0) / 3
    time = np.linspace(0, t, 100)
    sol = odeint(population_decrease, P0, time, args=(k,))
    P_t = sol[-1][0]
    return P_t - 5000

sol = root_scalar(residual, bracket=(0, 10), method='brentq')

print(round(sol.root, 5))
Erro na execução: name 'population_decrease' is not defined
Code executing (meta-llama/llama-3.3-70b-instruct_class/6): import numpy as np
from scipy.integrate import odeint

# Constants
R = 10  # Resistance in ohms
C = 4e-3  # Capacitance in farads
E0 = 85  # Amplitude of voltage source in volts
w = 150  # Angular frequency of voltage source in rad/s

# Initial condition
Q0 = -0.05  # Initial charge on capacitor in coulombs

# Time points
t = np.array([0, 0.2])

# Differential equation
def dQdt(Q, t, R, C, E0, w):
    return (E0 * np.cos(w * t) - Q / C) / R

# Solve ODE
sol = odeint(dQdt, Q0, t, args=(R, C, E0, w))

# Print charge at specified times
print("Charge at t = 0.0: ", round(sol[0][0], 5))
print("Charge at t = 0.2: ", round(sol[1][0], 5))
Code executing (meta-llama/llama-3.3-70b-instruct_class/7): import numpy as np
from scipy.integrate import odeint

# Constants
R = 12  # Resistance in ohms
L = 4   # Inductance in henries
E = 60  # Voltage amplitude in volts
omega = 0.5  # Angular frequency (30 degrees = pi/6 radians, but given as 30t, so omega = 0.5)

# Differential equation for current
def dIdt(I, t):
    return (E * np.sin(omega * t) - R * I) / L

# Initial condition: I(0) = 0
I0 = 0

# Time points to solve for
t = np.linspace(0, 3, 100)

# Solve ODE
I = odeint(dIdt, I0, t)

# Print current at t = 3
print(round(I[-1][0], 5))
Erro na execução: name 'E' is not defined
Code executing (meta-llama/llama-3.3-70b-instruct_class/8): import numpy as np
from scipy.integrate import odeint

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

T_env = 75
T0 = 185
t_data = 0.5
T_data = 150

# Calculate k from the data at t=0.5
k = -np.log((T_data - T_env) / (T0 - T_env)) / t_data

# Define time points for the solution
t = np.linspace(0, 0.75, 100)

# Solve ODE
sol = odeint(cooling, T0, t, args=(k, T_env))

# Find temperature at t = 0.75 (45 minutes)
T_45min = sol[-1][0]

print(round(T_45min, 5))
Code executing (meta-llama/llama-3.3-70b-instruct_class/9): import numpy as np
from scipy.integrate import solve_ivp

def model(t, P):
    return 0.03466 * P  # 0.03466 is the growth rate per minute, calculated as ln(2) / 20

P0 = [60]
t_span = (0, 200)  # Assuming the population will reach 20,000 cells within 200 minutes

sol = solve_ivp(model, t_span, P0, dense_output=True, rtol=1e-9, atol=1e-12)

def population_difference(t):
    return sol.sol(t)[0] - 20000

from scipy.optimize import root_scalar
result = root_scalar(population_difference, bracket=[0, 200], method='brentq')

print(round(result.root, 5))
Erro na execução: name 'sol' is not defined
Processadas 10/50 linhas
Code executing (meta-llama/llama-3.3-70b-instruct_class/10): import numpy as np
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

def model(t, P):
    r = 0.04  # Interest rate
    return r * P

def profit(t):
    P0 = 100000  # Initial investment
    sol = solve_ivp(model, (0, t), [P0], dense_output=True)
    return sol.sol(t)[0] - 300000  # Total amount after t years - target amount

result = root_scalar(profit, bracket=[0, 100], method='brentq')

print(round(result.root, 5))
Erro na execução: name 'model' is not defined
Code executing (meta-llama/llama-3.3-70b-instruct_class/11): from scipy.integrate import odeint
import numpy as np

def model(Q, t, r, C_in, V):
    dQdt = r * (C_in - Q / V)
    return dQdt

r = 5  # rate of brine entering and mixed solution draining in gal/min
C_in = 2  # concentration of salt in brine in lb/gal
V = 100  # volume of tank in gal
Q0 = 4  # initial amount of salt in tank in lb
t = np.linspace(0, 10)  # time points to solve for

sol = odeint(model, Q0, t, args=(r, C_in, V))

print(round(sol[-1][0], 5))
Code executing (meta-llama/llama-3.3-70b-instruct_class/12): import numpy as np
from scipy.integrate import odeint

def model(N, t, k):
    return k * N

def residual(k):
    N0 = 1000
    t = 2
    N_t = 3000
    sol = odeint(model, N0, [0, t], args=(k,))
    N_model = sol[-1][0]
    return N_model - N_t

k = 0.5772156649 # or use root_scalar to find k
# from scipy.optimize import root_scalar
# sol = root_scalar(residual, bracket=(0, 2), method='brentq')
# k = sol.root

N0 = 1000
t = 5
sol = odeint(model, N0, [0, t], args=(k,))

print(round(sol[-1][0], 5))
Code executing (meta-llama/llama-3.3-70b-instruct_class/13): from scipy.integrate import odeint
import numpy as np

def model(salt, t, flow_rate, volume):
    return -flow_rate * salt / volume

flow_rate = 5  # L/min
volume = 500  # L
initial_salt = 25  # kg
time = np.linspace(0, 30, 100)  # min


In [41]:
df=pd.read_csv('/content/drive/MyDrive/codigo_python/math_ODEsdataset_final_results.csv')
df.head(50)





#

,Index,Question,Proposed Solution,Answer,deepseek/deepseek-r1-distill-llama-70b_class,meta-llama/llama-3.3-70b-instruct_class,google/gemini-2.5-pro_class,google/gemma-3-27b-it_class,openai/gpt-4.1-mini_class,deepseek/deepseek-chat_class,deepseek/deepseek-r1-distill-llama-70b_exec_result,meta-llama/llama-3.3-70b-instruct_exec_result,google/gemini-2.5-pro_exec_result,google/gemma-3-27b-it_exec_result,openai/gpt-4.1-mini_exec_result,deepseek/deepseek-chat_exec_result
0,0,A population of protozoa grows at a constant r...,"We have dP/dt = kP Therefore dP/dt = 0,7944P ...",2.350000e+02,from scipy.integrate import solve_ivp\nimport ...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,234.9685,234.9685,234.9685,234.9685,234.9685,234.9685
1,1,A tank contains 1000 L of salt water with 15 k...,Let S(t) be the amount of salt (in kilograms...,1.230000e+01,from scipy.integrate import solve_ivp\nimport ...,```python\nfrom scipy.integrate import odeint\...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,12.281,12.281,12.281,12.281,12.281,12.281
2,2,A resistor R=10Ω and an inductor L=2H are conn...,"Using Kirchhoff's Voltage Law KVL, the sum of ...",0.000000e+00,To determine the initial current \( I(0) \) wh...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nR = 10\nL = 2\nV = 20\n\nI0 = 0 # ...,```python\nfrom scipy.integrate import solve_i...,exec_error,0.0,exec_error,0.0,0.0,exec_error
3,3,A 5μF capacitor is charged through a 10kΩ resi...,"In an RC charging circuit, Kirchhoff's voltag...",5.490000e-02,from scipy.integrate import solve_ivp\nfrom sc...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
4,4,An object is removed from an oven at 200°C and...,Let T(t) represent the temperature of the obje...,1.141900e+02,"To solve the cooling problem, we'll use Newton...",```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import odeint\...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,exec_error,114.2857,114.2886,114.2857,exec_error,exec_error
5,5,A certain village in Angola had a population ...,Let P(t) be the population at time t. The rate...,9.260000e+00,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
6,6,"Find the charge when t=0,2, in a series RC cir...","We have Rdq(t)/dt+1/C q=V Since R=10, C=4*10^(...",-5.290000e-02,To solve the problem of finding the charge in ...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,exec_error,10.0,-0.0534,exec_error,exec_error,exec_error
7,7,A resistor R=12Ω and an inductor L=4H are conn...,"Using Kirchhoff's Voltage Law (KVL), the sum o...",2.660000e-01,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,0.2661,exec_error,0.2662,0.2662,exec_error,0.2661
8,8,A roast chicken is removed from the oven when ...,Let T(t) represent the temperature of the roas...,1.364000e+02,To solve the problem of determining the temper...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import odeint\...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,exec_error,136.9292,exec_error,75.0,136.9293,exec_error
9,9,"Escherichia coli, a common bacteria found in t...","We have dP/dt = kP. Integrating both sides, we...",1.676300e+02,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,167.7168
10,10,"Suppose an amount of 100,000 kwanzas is invest...","We have dA/dt = kA Therefore dA/dt = 0,04A → ...",1.730000e+01,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
11,11,"At time t = 0, a tank contains 4 lb of salt di...",Let y(t) be the amount of salt (in pounds) aft...,8.110000e+01,from scipy.integrate import solve_ivp\nimport ...,```python\nfrom scipy.integrate import odeint\...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,81.1196,81.12,81.1196,81.1196,81.1196,81.1196
12,12,A bacterial culture grows at a rate proportion...,dP/dt = kP → P(t) = P0e^(kt) Given P(0)=1000 ...,1.558800e+04,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,15589.011,17922.8847,15589.011,15589.011,exec_error,exec_error
13,13,A tank contains 500L of brine with 25kg salt. ...,dS/dt=−5S/500=−S/100 S(t)=25e^(-t/100) S(30)=...,1.853000e+01,from scipy.integrate import solve_ivp\nimport ...,```python\nfrom scipy.integrate import odeint\...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,18.5205,18.5205,18.5205,18.5205,18.5205,18.5205
14,14,A hot metal cools from 300°F to 250°F in 10 mi...,T(t)=70+230e^(-kt) At t=10: 250=70+230e^(-10k...,1.944100e+02,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,156.2793,156.2793,156.2808,156.2793,156.2793,exec_error
15,15,A pizza cools from 400°F to 350°F in 5 minutes...,T(t)=75+325e^(-kt) At t=5: 350=75+325e^(-5k)→...,2.937300e+02,To solve the problem of determining the pizza'...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,exec_error,241.6022,241.6072,241.6022,241.6022,119.0433
16,16,"An amount of 50,000 dollar is invested at 5 p...","150,000=50.000e^(0.05t)→ t=ln(3)/0.05≈21.97 y...",2.197000e+01,To solve the problem of determining how long i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,21.971,exec_error,exec_error,exec_error
17,17,A tank contains 100L of water with 5kg salt. B...,Volume changes as dV/dt = 2 - 0.1sqrt(V) Salt...,2.814000e+01,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,19.5108,19.5108,19.5108,19.5226,19.5108,19.5109
18,18,A population of insects decreases at a rate pr...,"P(t) = 5000e^(-kt), use P(5) = 4000 to find k...",1.550000e+01,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
19,19,A tank contains 200 liters of salt water with ...,Let S(t) be the amount of salt (in grams) at t...,9.130000e+01,from scipy.integrate import odeint\nimport num...,```python\nfrom scipy.integrate import odeint\...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import odeint\...,97.0696,97.0696,97.0696,30.0,97.0696,97.0696
20,20,A resistor R=5Ω and an inductor L=1H are conne...,KVL gives: L dI/dt + RI = V → dI/dt + 5I = 1...,0.000000e+00,"To solve the problem, we analyze the circuit u...",```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nR = 5 # Resistance in ohms\nL ...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,exec_error,0.0,0.0,exec_error
21,21,A population of insects decreases at a rate pr...,dP/dt = -kP → P(t) = P0e^(-kt) Given P(0) =...,1.550000e+01,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
22,22,"In an RC circuit with R = 10kΩ and C = 2μ F , ...",Charge on capacitor: q(t) = CV(1 - e^(-t/RC)...,2.398000e-05,from scipy.integrate import solve_ivp\n\nR = 1...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,0.0,exec_error,exec_error,exec_error
23,23,A cup of coffee at 90 ° C is left in a room at...,Let T(t) be the temperature. T(t) = 20 + 70e...,5.850000e+01,To solve the problem using Newton's Law of Coo...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,exec_error,55.7143,55.7154,55.7143,55.7143,55.7154
24,24,A radioactive substance decays at a rate propo...,"A(t) = A0e^(-kt), 60 = 100e^(-10k) → e^(-10k...",1.360000e+01,"To solve the problem, we'll use the exponentia...",```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,13.5692,exec_error,exec_error
25,25,A 10mH inductor and a 20Ω resistor are connect...,KVL: L dI/dt + RI = V → dI/dt + 2000I = 10000...,5.000000e+00,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,4.9981,5.0,4.9981,exec_error,exec_error,exec_error
26,26,A cake is taken out of the oven at 350°F and p...,"T(t) = 70 + 280e^(-kt), T(10) = 300 → 230 = ...",2.573000e+02,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import odeint\...,exec_error,258.9286,258.9287,exec_error,258.9286,258.9286
27,27,"In 2020, an amount of 200,000 dollars was inv...","We have, dP/dt = -kP, where k = 0.10. Separa...",7.358000e+01,from scipy.integrate import solve_ivp\nimport ...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,200000.0,73598.5698,73598.5698,73598.5698,73598.5698,73598.5698
28,28,A bacterial culture doubles every 30 minutes. ...,"P(t) = 100e^(kt), P(30) = 200 → k = ln2/30 ≈ ...",6.400000e+03,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,6399.8152,6399.8152,6399.6471,6399.8082,810022.0883,6399.8152
29,29,A radioactive sample has a half-life of 12 day...,"A(t) = A0e^(-kt), 1/2 = e^(-12k) → k = ln2/12...",3.990000e+01,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,39.8747,exec_error,exec_error,exec_error
30,30,A tank contains 100 gallons of water. In erro...,Let x represent the number of pounds of salt i...,1.350000e+01,To solve the problem of determining how long i...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
31,31,An amount of 1 dollar is invested at 4 percen...,We are given the continuous compounding formul...,1.733000e+01,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,17.3288,exec_error,exec_error,exec_error
32,32,A body whose temperature is 180° is immersed i...,"Using Newton's Law of Cooling, we have the for...",2.000000e+00,"To solve the problem using numerical methods, ...",```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
33,33,The temperature in a room is initially 70°. A ...,"Using Newton’s Law of Cooling, with T(0) = 7...",5.000000e+01,The outdoor temperature is 50°F.\n\n```python\...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
34,34,The rate at which radioactive nuclei decay is ...,We have N(t) = N0 e^(-kt) We know that half o...,1.250000e+01,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,12.5145,12.5145,exec_error,12.5145,12.5145,exec_error
35,35,The population of Huambo town increases at a...,We have the population growth given by dP/dt =...,4.082400e+01,"To solve the population growth problem, we'll ...",```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,exec_error,44940.89,40833.336,47617.3756,exec_error,exec_error
36,36,"An investment of 1,000,000 kwanzas loses value...",The continuous decay rate is described by the ...,2.800000e+01,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,exec_error,exec_error,27.7278,exec_error,exec_error,exec_error
37,37,A man with a parachute jumps at a great height...,"We are given: W = 160lb, 0 ≤ t < 10, g = 32ft...",1.601000e+01,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,16.0096,exec_error,16.0096,exec_error,exec_error,360.8465
38,38,Find rate of interest per year compounded con...,Let: A(t): amount at time t A(0) = 10...,5.493000e+00,To find the continuous compounding rate that c...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.opti...,```python\nfrom scipy.optimize import root_sca...,```python\nimport numpy as np\nfrom scipy.opti...,exec_error,exec_error,exec_error,0.0549,0.0549,exec_error
39,39,The rate at which a certain substance dissolve...,The rate at which a certain substance dissolve...,7.140000e+00,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,7.1429,exec_error,exec_error,exec_error,exec_error,exec_error

In [42]:
df.drop(columns=[
    'Index',
    'Proposed Solution',
    'deepseek/deepseek-r1-distill-llama-70b_class',
    'meta-llama/llama-3.3-70b-instruct_class',
    'google/gemini-2.5-pro_class',
    'google/gemma-3-27b-it_class',
    'deepseek/deepseek-chat_class',
    'openai/gpt-4.1-mini_class'
], inplace=True)

df

,Question,Answer,deepseek/deepseek-r1-distill-llama-70b_exec_result,meta-llama/llama-3.3-70b-instruct_exec_result,google/gemini-2.5-pro_exec_result,google/gemma-3-27b-it_exec_result,openai/gpt-4.1-mini_exec_result,deepseek/deepseek-chat_exec_result
0,A population of protozoa grows at a constant r...,2.350000e+02,234.9685,234.9685,234.9685,234.9685,234.9685,234.9685
1,A tank contains 1000 L of salt water with 15 k...,1.230000e+01,12.281,12.281,12.281,12.281,12.281,12.281
2,A resistor R=10Ω and an inductor L=2H are conn...,0.000000e+00,exec_error,0.0,exec_error,0.0,0.0,exec_error
3,A 5μF capacitor is charged through a 10kΩ resi...,5.490000e-02,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
4,An object is removed from an oven at 200°C and...,1.141900e+02,exec_error,114.2857,114.2886,114.2857,exec_error,exec_error
5,A certain village in Angola had a population ...,9.260000e+00,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
6,"Find the charge when t=0,2, in a series RC cir...",-5.290000e-02,exec_error,10.0,-0.0534,exec_error,exec_error,exec_error
7,A resistor R=12Ω and an inductor L=4H are conn...,2.660000e-01,0.2661,exec_error,0.2662,0.2662,exec_error,0.2661
8,A roast chicken is removed from the oven when ...,1.364000e+02,exec_error,136.9292,exec_error,75.0,136.9293,exec_error
9,"Escherichia coli, a common bacteria found in t...",1.676300e+02,exec_error,exec_error,exec_error,exec_error,exec_error,167.7168
10,"Suppose an amount of 100,000 kwanzas is invest...",1.730000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
11,"At time t = 0, a tank contains 4 lb of salt di...",8.110000e+01,81.1196,81.12,81.1196,81.1196,81.1196,81.1196
12,A bacterial culture grows at a rate proportion...,1.558800e+04,15589.011,17922.8847,15589.011,15589.011,exec_error,exec_error
13,A tank contains 500L of brine with 25kg salt. ...,1.853000e+01,18.5205,18.5205,18.5205,18.5205,18.5205,18.5205
14,A hot metal cools from 300°F to 250°F in 10 mi...,1.944100e+02,156.2793,156.2793,156.2808,156.2793,156.2793,exec_error
15,A pizza cools from 400°F to 350°F in 5 minutes...,2.937300e+02,exec_error,241.6022,241.6072,241.6022,241.6022,119.0433
16,"An amount of 50,000 dollar is invested at 5 p...",2.197000e+01,exec_error,exec_error,21.971,exec_error,exec_error,exec_error
17,A tank contains 100L of water with 5kg salt. B...,2.814000e+01,19.5108,19.5108,19.5108,19.5226,19.5108,19.5109
18,A population of insects decreases at a rate pr...,1.550000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
19,A tank contains 200 liters of salt water with ...,9.130000e+01,97.0696,97.0696,97.0696,30.0,97.0696,97.0696
20,A resistor R=5Ω and an inductor L=1H are conne...,0.000000e+00,exec_error,exec_error,exec_error,0.0,0.0,exec_error
21,A population of insects decreases at a rate pr...,1.550000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
22,"In an RC circuit with R = 10kΩ and C = 2μ F , ...",2.398000e-05,exec_error,exec_error,0.0,exec_error,exec_error,exec_error
23,A cup of coffee at 90 ° C is left in a room at...,5.850000e+01,exec_error,55.7143,55.7154,55.7143,55.7143,55.7154
24,A radioactive substance decays at a rate propo...,1.360000e+01,exec_error,exec_error,exec_error,13.5692,exec_error,exec_error
25,A 10mH inductor and a 20Ω resistor are connect...,5.000000e+00,4.9981,5.0,4.9981,exec_error,exec_error,exec_error
26,A cake is taken out of the oven at 350°F and p...,2.573000e+02,exec_error,258.9286,258.9287,exec_error,258.9286,258.9286
27,"In 2020, an amount of 200,000 dollars was inv...",7.358000e+01,200000.0,73598.5698,73598.5698,73598.5698,73598.5698,73598.5698
28,A bacterial culture doubles every 30 minutes. ...,6.400000e+03,6399.8152,6399.8152,6399.6471,6399.8082,810022.0883,6399.8152
29,A radioactive sample has a half-life of 12 day...,3.990000e+01,exec_error,exec_error,39.8747,exec_error,exec_error,exec_error
30,A tank contains 100 gallons of water. In erro...,1.350000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
31,An amount of 1 dollar is invested at 4 percen...,1.733000e+01,exec_error,exec_error,17.3288,exec_error,exec_error,exec_error
32,A body whose temperature is 180° is immersed i...,2.000000e+00,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
33,The temperature in a room is initially 70°. A ...,5.000000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
34,The rate at which radioactive nuclei decay is ...,1.250000e+01,12.5145,12.5145,exec_error,12.5145,12.5145,exec_error
35,The population of Huambo town increases at a...,4.082400e+01,exec_error,44940.89,40833.336,47617.3756,exec_error,exec_error
36,"An investment of 1,000,000 kwanzas loses value...",2.800000e+01,exec_error,exec_error,27.7278,exec_error,exec_error,exec_error
37,A man with a parachute jumps at a great height...,1.601000e+01,16.0096,exec_error,16.0096,exec_error,exec_error,360.8465
38,Find rate of interest per year compounded con...,5.493000e+00,exec_error,exec_error,exec_error,0.0549,0.0549,exec_error
39,The rate at which a certain substance dissolve...,7.140000e+00,7.1429,exec_error,exec_error,exec_error,exec_error,exec_error
40,A 12 volt battery is connected to a series cir...,1.200000e+00,1.1996,1.2,1.1996,1.1996,exec_error,1.1996
41,The population of Ussinda Katota village of Tc...,2.668200e+04,135001.1447,26666.6673,exec_error,exec_error,exec_error,exec_error
42,The air in a room whose volume is 10000 cubic ...,7.230000e-02,exec_error,7.2313,0.0723,0.0723,exec_error,0.0723
43,A body weighing 8 lb falls from rest toward th...,4.000000e+00,exec_error,4.0,3.9992,16.0981,exec_error,3.9995
44,A sponge dries in an open air at a rate that i...,1.297000e+02,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
45,A 3μF capacitor is charged through a 15kΩ resi...,1.295000e-02,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
46,A wooden block weighing 50 lb is released from...,1.966080e+01,exec_error,exec_error,19.7824,19.7824,exec_error,19.7824
47,A boat is being towed at the rate of 18 ft/se...,1.162700e+01,11.6284,11.627,11.628,17.3192,exec_error,11.6241
48,An object on a sled is pulled by a force of 10...,4.970000e+00,4.9657,0.7233,4.9657,0.7233,exec_error,4.9666
49,"In 2024, an investment of 15,000,000 kwanzas w...",9.097500e+06,9097965.0561,9097965.0561,9097959.9055,9097965.0561,exec_error,9097965.0561

In [44]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import sklearn

print(f"🔍 Versão do scikit-learn: {sklearn.__version__}")

ABS_TOL = 0.1
REL_TOL = 0.05

df = df  # Substitua pelo caminho correto
answer_col = "Answer"
model_cols = [col for col in df.columns if col.endswith('_exec_result')]

metrics = []

for model in model_cols:
    y_true = []
    y_pred = []
    acc_count = 0
    total = 0

    for truth, pred in zip(df[answer_col], df[model]):
        total += 1
        if isinstance(pred, str) and "exec_error" in pred:
            continue
        try:
            pred = float(pred)
            truth = float(truth)
        except:
            continue

        y_true.append(truth)
        y_pred.append(pred)

        if abs(pred - truth) <= ABS_TOL or abs(pred - truth) / max(abs(truth), 1e-8) <= REL_TOL:
            acc_count += 1

    if len(y_true) == 0:
        metrics.append({
            "model": model,
            "accuracy (%)": 0.0 if total > 0 else None,
            "mae (%)": None,
            "mse (%)": None,
            "rmse (%)": None,
            "r2 (%)": None,


        })
        continue

    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    metrics.append({
        "model": model,
        "accuracy (%)": round((acc_count / total) * 100,1),
        "mae (%)": round(mae * 100,1),
        "mse (%)": round(mse * 100,1),
        "rmse (%)": round(rmse * 100,1),
        "r2 (%)": round(r2 * 100,1 ),


    })

metrics_df = pd.DataFrame(metrics)
metrics_df = metrics_df.sort_values(by="accuracy (%)", ascending=False)

print("📊 Métricas de avaliação por modelo (em %):")
print(metrics_df.to_string(index=False))

🔍 Versão do scikit-learn: 1.6.1
📊 Métricas de avaliação por modelo (em %):
                                             model  accuracy (%)   mae (%)      mse (%)   rmse (%)     r2 (%)
                 google/gemini-2.5-pro_exec_result          50.0  370607.9 2.280700e+10  1510198.6      100.0
     meta-llama/llama-3.3-70b-instruct_exec_result          34.0  449525.1 2.750968e+10  1658604.1      100.0
                 google/gemma-3-27b-it_exec_result          34.0  435071.4 2.739172e+10  1655044.3      100.0
                deepseek/deepseek-chat_exec_result          32.0  354899.3 2.574424e+10  1604501.1      100.0
deepseek/deepseek-r1-distill-llama-70b_exec_result          30.0 1543822.3 2.585191e+11  5084477.8       99.9
                   openai/gpt-4.1-mini_exec_result          20.0 5160365.9 3.830673e+12 19572104.8 -1732786.6