
token 23
 http://127.0.0.1:9997/lab?token=f92d7bda0618c680b91069ba9333dae4686b5bac989f4756

In [ ]:
 !pip install ollama

Requirement already satisfied: ollama in /usr/local/lib/python3.11/dist-packages (0.5.1)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.11/dist-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in /usr/local/lib/python3.11/dist-packages (from ollama) (2.11.7)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->ollama) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->ollama) (2025.7.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27->ollama) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9->ollama) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9->ollama) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.9->ollama) (0.4.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.27->ollama) (1.3.1)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn import preprocessing
import scipy
import sympy
from sympy import *
from sympy.solvers.ode.systems import dsolve_system
from sympy import init_printing
init_printing()
from sympy import symbols, Eq, Function, dsolve
from sympy import init_printing
init_printing()
import math
from scipy.integrate import odeint
from scipy.integrate import odeint
from scipy.integrate import solve_ivp  # or nothing
import os
import random
import torch
import json
import requests
import time
import hashlib
from typing import List, Dict, Any, Tuple, Literal, Union
from tqdm import tqdm
import ast
from requests.exceptions import ConnectionError
from http.client import RemoteDisconnected
#from x_llm import llm_query
import ollama
import weakref
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pwd

/content

In [ ]:
DEFAULT_MODEL_PARAMS = {'top_k':1,'temperature':0.1, 'top_p':0.0001}

# CACHE_PATH = os.path.join( 'tmp', "cache_llm_respostas_ANALISES.json" )
CACHE_PATH = "/content/drive/MyDrive/codigo_python/cache_llm_respostas_ANALISES.json"
# HOST_OLLAMA = "10.10.10.106:11434"
HOST_OLLAMA = 'local'
SAVE_CACHE_INTERVAL=1
SEED = 42
DEFAULT_TIME_SLEEP = 1

def fixar_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    # torch.manual_seed(seed)

    # if torch.cuda.is_available():
    #     # torch.cuda.manual_seed(seed)
    #     # torch.cuda.manual_seed_all(seed)  # para múltiplas GPUs
    #     torch.backends.cudnn.deterministic = True
    #     torch.backends.cudnn.benchmark = False



LLMModelsType = Union[
    str,
    Tuple[str, Literal['ollama', 'openrouter']]
]

class LLMInference:
    def __init__(self, api_key: str, models: List[LLMModelsType] = [], models_params: List[Dict[str, str]] = None,
                 system_prompt: str = None,
                 structured_output_instructions: Dict[str, Any] = None,
                 use_cache: bool = True,
                 cache_interval:int = 10,
                 cache_path: str = CACHE_PATH,
                 default_model_type:Literal['ollama', 'openrouter'] = 'ollama',
                 fix_seed:int = 42,
                 host_ollama: str = HOST_OLLAMA,
                 default_time_sleep: int = DEFAULT_TIME_SLEEP):
        """
        Initialize the batch inference class using OpenAI client for OpenRouter.

        Args:
            api_key (str): Your OpenRouter API key.
            models (List[str]): List of model names to query.
            system_prompt (str): Common system prompt for all queries.
            structured_output_instructions (Dict[str, Any]): Instructions to guide the output structure.
        """

        self.models = models
        if models_params is None:
            self.models_params = [DEFAULT_MODEL_PARAMS]*len(models)
        else:
            self.models_params = models_params
        self.system_prompt = system_prompt
        self.structured_output_instructions = structured_output_instructions
        self.api_key = api_key

        if fix_seed is not None:
            fixar_seed( fix_seed )

        self.seed = fix_seed
        self.default_model_type = default_model_type
        self.use_cache = use_cache
        self.cache_interval = cache_interval
        self.cache_path = cache_path
        self.host_ollama = host_ollama
        self.cache_counter = 0
        self.default_time_sleep = default_time_sleep

        if os.path.exists(self.cache_path):
            with open(self.cache_path) as f:
                self.cache = json.load(f)
                print('cache lido', flush=True)
        else:
            self.cache = {}

        weakref.finalize(self, self._save_cache)


    def _create_messages(self, user_prompt: str) -> List[Dict[str, str]]:
        """
        Create the message payload.

        Args:
            user_prompt (str): The user-specific prompt.

        Returns:
            List[Dict[str, str]]: Messages to send to the model.
        """
        messages = []
        if self.system_prompt:
            messages.append( {"role": "system", "content": self.system_prompt} )
        messages.append({"role": "user", "content": user_prompt})
        if self.structured_output_instructions:
            messages.append( {"role": "user", "content": f"Format your output according to: {self.structured_output_instructions}"} )
        return messages

    def _query_model_raw_openrouter(self, model: str, model_params: Dict[str,Any], user_prompt: str, max_retries:int=5) -> str:
        """
        Query a single model using OpenAI client.

        Args:
            model (str): Model name.
            user_prompt (str): User-specific prompt.

        Returns:
            str: Model's output content.
        """
        # completion = self.client.chat.completions.create(
        #     model=model,
        #     messages=self._create_messages(user_prompt),
        #     top_k=1,
        #     temperature=0.1
        # )
        # return completion.choices[0].message.content

        url = "https://openrouter.ai/api/v1/chat/completions"
        headers = {
        "Authorization": f"Bearer {self.api_key}",
        "Content-Type": "application/json"
        }
        payload = {
        "model": model,
        "messages": self._create_messages(user_prompt)
        }
        payload.update(model_params)


        retry_count = 0

        while True:
            try:
                response = requests.post(url, headers=headers, json=payload, timeout = 300)
                response.raise_for_status()  # levanta erro se status >= 400
                if self.default_time_sleep > 0:
                    time.sleep(self.default_time_sleep)
                # print("Sucesso:", response.status_code)
                break  # sai do loop se a requisição for bem-sucedida

            except (ConnectionError, RemoteDisconnected) as e:
                retry_count += 1
                if retry_count > max_retries:
                    print("Max retries reached. Exiting...")
                    raise
                print("Erro de conexao:", e)
                print(f"Erro de conexão detectado ({retry_count}/{max_retries}): {e}")
                print("Aguardando 60 segundos antes de tentar novamente...", flush=True)
                time.sleep(60)

            except Exception as e:
                print("Erro inesperado:", e)
                raise
                # break  # interrompe se for outro erro que não de conexão


        # response = requests.post(url, headers=headers, json=payload, timeout = 300)
        # response.raise_for_status()  # dispara exceção se status >= 400

        return response.json()['choices'][0]['message']['content']

    def _query_ollama(self, model: str, model_params: Dict[str, Any], user_prompt: str) -> str:
        if self.host_ollama == 'local':
            client = ollama
        else:
            client = ollama.Client(host=self.host_ollama)


        if self.seed is not None and not 'seed' in model_params:
            model_params['seed'] = self.seed

        response = client.generate(
            model=model,
            prompt=user_prompt,
            stream=False,
            options=model_params,
        )

        return response['response']
    def _save_cache( self ):
        with open(self.cache_path, "w") as f:
            json.dump(self.cache, f, indent=2)

    def query_model(self, model: str, model_params: Dict[str, Any], user_prompt: str, model_type:Literal['ollama', 'openrouter'] = None, max_retries:int=5 ) -> str:
        key = hashlib.md5(user_prompt.encode()+model.encode()+str(model_params).encode()).hexdigest()
        if key in self.cache:
            print( 'USed from cache.', flush=True)
            return self.cache[key]
        try:
            # response_TXT = call_ollama(MODEL, prompt)


            if model_type is None:
                model_type = self.default_model_type
            if model_type == 'ollama':
                response_TXT =  self._query_ollama(model, model_params, user_prompt)
            elif model_type == 'openrouter':
                continua = True
                while continua:
                    try:
                        response_TXT  = self._query_model_raw_openrouter(model, model_params, user_prompt, max_retries=max_retries)
                        continua = False
                    except requests.exceptions.HTTPError as e:
                        if e.response is not None and e.response.status_code == 429:
                            self._save_cache()
                            print("Erro 429: too many requests / rate limit exceeded. Sleeping...")
                            time.sleep( 60 )
                        else:
                            raise
            else:
                raise ValueError(f"Unsupported model type: {model_type}. Use 'ollama' or 'openrouter'.")
        except Exception as e:
            self._save_cache()
            raise

        reply = response_TXT.strip()
        self.cache[key] = reply
        self.cache_counter+=1
        if self.cache_counter % SAVE_CACHE_INTERVAL == 0:
            self._save_cache()
            print('Cache saved to disk.', flush=True)
        # print(f"Cache hit: {self.cache_counter} - {key}", flush=True)
        return reply

    def generate_outputs(self, dataset: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
        """
        Generate outputs for each model given a labeled dataset.

        Args:
            dataset (List[Dict[str, Any]]): List of data points with 'text' and 'label'.

        Returns:
            Dict[str, List[Dict[str, Any]]]: Outputs organized by model name.
        """
        all_outputs = {model: [] for model in self.models}

        for data_point in tqdm(dataset):
            user_prompt = f"Text: {data_point['text']}\nLabel: {data_point['label']}"

            for model, model_params in zip(self.models, self.models_params):
                try:
                    print(f"Querying model {model}...")
                    output = self.query_model(model, model_params, user_prompt)
                    all_outputs[model].append({
                        "input": data_point,
                        "output": output
                    })
                    time.sleep(1)  # Sleep between requests to be polite
                except Exception as e:
                    print(f"Error querying model {model}: {e}")
                    all_outputs[model].append({
                        "input": data_point,
                        "output": {"error": str(e)}
                    })

        return all_outputs

In [ ]:
DEFAULT_MODEL_PARAMS = {'top_k':1,'temperature':0.1, 'top_p':0.0001}

CACHE_PATH = "/content/drive/MyDrive/codigo_python/cache_llm_respostas_ANALISES.json"
#CACHE_PATH = "/content/drive/MyDrive/codigo_python/cache_llm_respostas_ANALISES.json"
# HOST_OLLAMA = "10.10.10.106:11434"
MY_KEY = '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'

my_llm = LLMInference(
            api_key = MY_KEY,
            use_cache = True,
            cache_interval = 10,
            cache_path = CACHE_PATH,
            default_model_type = 'openrouter', # 'ollama' ou 'openrouter'
            fix_seed = 42,
            host_ollama = 'local',
            default_time_sleep = 1
        )

cache lido

In [ ]:
df=pd.read_csv('/content/math_ODEsdataset_csv.txt')
df.head(5)

,Index,Question,Proposed Solution,Answer
0,0,A population of protozoa grows at a constant r...,"We have dP/dt = kP Therefore dP/dt = 0,7944P ...",235.0000
1,1,A tank contains 1000 L of salt water with 15 k...,Let S(t) be the amount of salt (in kilograms...,12.3000
2,2,A resistor R=10Ω and an inductor L=2H are conn...,"Using Kirchhoff's Voltage Law KVL, the sum of ...",0.0000
3,3,A 5μF capacitor is charged through a 10kΩ resi...,"In an RC charging circuit, Kirchhoff's voltag...",0.0549
4,4,An object is removed from an oven at 200°C and...,Let T(t) represent the temperature of the obje...,114.1900

In [ ]:
def ODE_modelling(model, text):
    prompt = f"""[Instruction]
Assume you are Dr. LLM – an expert in Ordinary Differential Equations (ODEs), with extensive experience in formulating ODE models from natural language descriptions that can be  solved using a solver. Your primary task is to convert a given open-ended math problem into a complete Python code ready to executed. The Python code Should provide a numeric answer when executed.Choose the most appropriate solver (`solve_ivp` or `odeint`) for effectively tackling each Ordinary Differential Equation (ODE) problem.
This Python code should adhere to the following criteria:
1. Your response should be a Python Code that uses one of the following solvers appropriately: `solve_ivp` or  `odeint` based on the nature of the problem.
2. The code should be a final-state approach without displaying intermediate steps or variables.
3. The final result must be rounded to exactly 5 significant figures or 5 decimal places.
4. The response must consist solely of valid Python code, ready to execute without modification.
5. Ensure all LaTeX math expressions in the problem are interpreted and translated into correct mathematical expressions in Python.



Here comes 3  examples:

=====================================================================================================================================================================================================================================================================================================================================================================
[Example 1. A population of protozoa grows at a constant relative rate of 0.44 per individual per day.
On day zero, the population consists of five  protozoa.
Calculate the population size after 8 days?]

Here are the instruction and Python code that solves the given problem and meets the specified requirements:

<think>  **Problem Analysis**:
# Step 1: Interpret the problem.
# - The population grows at a **constant relative rate** of 0.44 per day, which implies exponential growth.
# - This gives the ODE: dP/dt = 0.44 * P, where P(t) is the population at time t (in days).
# - The initial condition is P(0) = 5 (five protozoa at day zero).
# - We need to compute P(8), the population at t = 8 days.

# Step 2: Use solve_ivp to numerically solve the ODE.
# - Define the function f(t, P) = 0.44 * P.
# - Solve over the interval [0, 8] with initial value P(0) = 5.
# - Extract and print the value at t = 8 rounded to 4 decimal places.

</think> (Output-Solution)
from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.44 * P
P0 = [5]
t_span = (0, 8)
sol = solve_ivp(model, t_span, P0, t_eval=[8])
print(round(sol.y[0][0], 4))

=============================================================================================================================================================================================================
[Example 2. A body whose temperature is 20° is placed in a medium which is kept at a constant temperature of 60°. In 5 minute, the body's temperature has risen to 30°. How long will it take for the body's temperature to increase to 40°?]

Here are the instruction and Python code that solves the given problem and meets the specified requirements:

 <think>  **Problem Analysis**:
# Step 1: Newton's Law of Cooling/Heating: dT/dt = -k(T - T_env)
# Here T_env = 60°C (constant medium temperature)
# Initial temperature T(0) = 20°C
# After 5 min, T(5) = 30°C
# Find time t when T(t) = 40°C
# Step 2:
# - Calculate k from the data at t=5
# - Define a residual function for temperature difference at time t
# - Use root finding to get t when temperature reaches 40°C


</think> (Output-Solution)
import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def residual(t):
    T_env = 60
    T0 = 20
    k = -np.log((30 - T_env) / (T0 - T_env)) / 5  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(cooling, T0, time, args=(k, T_env))
    T_t = sol[-1][0]
    return T_t - 40

sol = root_scalar(residual, bracket=(0, 50), method='bisect')

print(round(sol.root, 5))

=======================================================================================================================================================================================
[Example 3. A 6μF capacitor is charged through a 30kΩ resistor from a 48V battery. Calculate how long will
it take for the voltage across the capacitor to reach 12V ?]

Here are the instruction and Python code that solves the given problem and meets the specified requirements:

 <think>  **Problem Analysis**:
# Problem: A 6μF capacitor is charged through a 30kΩ resistor from a 48V battery.
# Goal: Find time t when the voltage across the capacitor reaches 12V.
# Physical model: RC charging circuit.
# ODE: dV/dt = (1/RC) * (V_batt - V)
# Initial condition: V(0) = 0
# Target condition: V(t) = 12
# Use solve_ivp to solve numerically and root_scalar to find exact time.

</think>(Output-Solution)

from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

R = 30000          # Resistance in ohms
C = 6e-6           # Capacitance in farads
V_batt = 48        # Battery voltage in volts
V_target = 12      # Target voltage in volts

def dVdt(t, V):
    return (1 / (R * C)) * (V_batt - V)

sol = solve_ivp(dVdt, t_span=(0, 1), y0=[0], dense_output=True, rtol=1e-9, atol=1e-12)

def voltage_difference(t):
    return sol.sol(t)[0] - V_target

result = root_scalar(voltage_difference, bracket=[0, 1], method='brentq')

print(f"(result.root:.5f)")



========================================================================================================================================================================================================
The following sentences  are forbidden:
”
This code solves the  problem for the given differential equation using 'solve_ivp' from SciPy;
This code solves the  problem for the given differential equation using ‘odeint‘ from SciPy;

Please avoid the above sentences.
========================================================================================================================================================================================================
Take it easy and have a deep breath before answering the question. This won't be a challenge for you atall.


Here comes the question:
{text}

Your response:
"""
    response = my_llm.query_model( model, DEFAULT_MODEL_PARAMS, prompt)
    print("**************", model)
    print(response)
    print("************")
    return response

In [ ]:
text = df.iloc[0]['Question']
model = 'mistralai/mistral-small-3.2-24b-instruct:free'
ODE_modelling(model, text)

USed from cache.
************** mistralai/mistral-small-3.2-24b-instruct:free
from scipy.integrate import solve_ivp

def model(t, P):
    return 0.7944 * P

P0 = [2]
t_span = (0, 6)
sol = solve_ivp(model, t_span, P0, t_eval=[6])
print(round(sol.y[0][0], 5))
************

'from scipy.integrate import solve_ivp\n\ndef model(t, P):\n    return 0.7944 * P\n\nP0 = [2]\nt_span = (0, 6)\nsol = solve_ivp(model, t_span, P0, t_eval=[6])\nprint(round(sol.y[0][0], 5))'

In [ ]:
import pandas as pd
import os
import hashlib
import json
from pathlib import Path

# Caminho do arquivo de cache
CACHE_FILE = Path('/content/drive/MyDrive/codigo_python/math_ODEsdataset_csv.txt')

# Garante que o diretório de cache existe
CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)

# Tenta carregar o cache existente
cache = {}
if CACHE_FILE.exists():
    print('🔁 Cache lido dos códigos!')
    try:
        with open(CACHE_FILE, 'r') as f:
            cache = json.load(f)
        print(f"🔹 Cache carregado com {len(cache)} entradas")
    except Exception as e:
        print(f"⚠️ Erro ao carregar cache: {e}")
        print("🔸 Iniciando cache novo.")

def get_cache_key(model, question):
    """Gera chave única para cache"""
    return hashlib.md5(f"{model}_{question}".encode()).hexdigest()

# Carrega o dataset
df = pd.read_csv('/content/math_ODEsdataset_csv.txt')

# Lista de modelos
models = [
    'meta-llama/llama-3.1-405b-instruct:free',
    'google/gemma-3-27b-it:free',
    'deepseek/deepseek-r1-distill-llama-70b:free',
    'mistralai/mistral-small-3.2-24b-instruct:free',
    'x-ai/grok-3-mini-beta',
    'google/gemini-2.5-pro-preview'
]

# Processa cada modelo
for model in models:
    responses = []
    print(f"\n{'='*60}")
    print(f"▶️ Processando modelo: {model}")
    print(f"{'='*60}")

    model_col = model + '_class'
    existing_responses = df[model_col].tolist() if model_col in df.columns else [None] * len(df)

    for index, row in df.iterrows():
        question = str(row['Question'])
        cache_key = get_cache_key(model, question)

        # Usa cache
        if cache_key in cache:
            responses.append(cache[cache_key])
            print(f"✓ Cache usado para índice {index}")
            continue

        # Usa resposta existente (não é 'error' nem vazia)
        if existing_responses[index] not in [None, 'error', '']:
            responses.append(existing_responses[index])
            cache[cache_key] = existing_responses[index]
            print(f"↻ Reuso da resposta existente para índice {index}")
            continue

        # Gera nova resposta
        result = 'error'
        for attempt in range(3):
            try:
                rsp = ODE_modelling(model, question)
                if rsp != 'error':
                    result = rsp
                    break
            except Exception as e:
                print(f"⚠️ Erro na tentativa {attempt+1} no índice {index}: {e}")

        responses.append(result)
        cache[cache_key] = result

        # Salva o cache a cada 20 linhas
        if (index + 1) % 20 == 0:
            with open(CACHE_FILE, 'w') as f:
                json.dump(cache, f)
            print(f"💾 Cache salvo após linha {index+1}")

    # Atualiza coluna do modelo
    df[model_col] = responses

    # Salva cache após cada modelo
    with open(CACHE_FILE, 'w') as f:
        json.dump(cache, f)
    print(f"✅ Cache salvo após processar modelo: {model}")

# Garante que a pasta 'results' existe
os.makedirs('results', exist_ok=True)

# Salva o CSV final
df.to_csv('math_ODEsdataset_csv.txt_models', index=False)
print("🎯 Processamento completo! CSV salvo.")

🔁 Cache lido dos códigos!
🔹 Cache carregado com 608 entradas

============================================================
▶️ Processando modelo: meta-llama/llama-3.1-405b-instruct:free
============================================================
✓ Cache usado para índice 0
✓ Cache usado para índice 1
✓ Cache usado para índice 2
✓ Cache usado para índice 3
✓ Cache usado para índice 4
✓ Cache usado para índice 5
✓ Cache usado para índice 6
✓ Cache usado para índice 7
✓ Cache usado para índice 8
✓ Cache usado para índice 9
✓ Cache usado para índice 10
✓ Cache usado para índice 11
✓ Cache usado para índice 12
✓ Cache usado para índice 13
✓ Cache usado para índice 14
✓ Cache usado para índice 15
✓ Cache usado para índice 16
✓ Cache usado para índice 17
✓ Cache usado para índice 18
✓ Cache usado para índice 19
✓ Cache usado para índice 20
✓ Cache usado para índice 21
✓ Cache usado para índice 22
✓ Cache usado para índice 23
✓ Cache usado para índice 24
✓ Cache usado para índice 25
✓ Cache usado para índice 26
✓ Cache usado para índice 27
✓ Cache usado para índice 28
✓ Cache usado para índice 29
✓ Cache usado para índice 30
✓ Cache usado para índice 31
✓ Cache usado para índice 32
✓ Cache usado para índice 33
✓ Cache usado para índice 34
✓ Cache usado para índice 35
✓ Cache usado para índice 36
✓ Cache usado para índice 37
✓ Cache usado para índice 38
✓ Cache usado para índice 39
✓ Cache usado para índice 40
✓ Cache usado para índice 41
✓ Cache usado para índice 42
✓ Cache usado para índice 43
✓ Cache usado para índice 44
✓ Cache usado para índice 45
✓ Cache usado para índice 46
✓ Cache usado para índice 47
✓ Cache usado para índice 48
✓ Cache usado para índice 49
✅ Cache salvo após processar modelo: meta-llama/llama-3.1-405b-instruct:free

============================================================
▶️ Processando modelo: google/gemma-3-27b-it:free
============================================================
✓ Cache usado para índice 0
✓ Cache usado para índice 1
✓ Cache usado para índice 2
✓ Cache usado para índice 3
✓ Cache usado para índice 4
✓ Cache usado para índice 5
✓ Cache usado para índice 6
✓ Cache usado para índice 7
✓ Cache usado para índice 8
✓ Cache usado para índice 9
✓ Cache usado para índice 10
✓ Cache usado para índice 11
✓ Cache usado para índice 12
✓ Cache usado para índice 13
✓ Cache usado para índice 14
✓ Cache usado para índice 15
✓ Cache usado para índice 16
✓ Cache usado para índice 17
✓ Cache usado para índice 18
✓ Cache usado para índice 19
✓ Cache usado para índice 20
✓ Cache usado para índice 21
✓ Cache usado para índice 22
✓ Cache usado para índice 23
✓ Cache usado para índice 24
✓ Cache usado para índice 25
✓ Cache usado para índice 26
✓ Cache usado para índice 27
✓ Cache usado para índice 28
✓ Cache usado para índice 29
✓ Cache usado para índice 30
✓ Cache usado para índice 31
✓ Cache usado para índice 32
✓ Cache usado para índice 33
✓ Cache usado para índice 34
✓ Cache usado para índice 35
✓ Cache usado para índice 36
✓ Cache usado para índice 37
✓ Cache usado para índice 38
✓ Cache usado para índice 39
✓ Cache usado para índice 40
✓ Cache usado para índice 41
✓ Cache usado para índice 42
✓ Cache usado para índice 43
✓ Cache usado para índice 44
✓ Cache usado para índice 45
✓ Cache usado para índice 46
✓ Cache usado para índice 47
✓ Cache usado para índice 48
✓ Cache usado para índice 49
✅ Cache salvo após processar modelo: google/gemma-3-27b-it:free

============================================================
▶️ Processando modelo: deepseek/deepseek-r1-distill-llama-70b:free
============================================================
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.7944 * P

P0 = [2]
t_span = (0, 6)
sol = solve_ivp(model, t_span, P0, t_eval=[6])
print(round(sol.y[0][0], 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import odeint
import numpy as np

def model(S, t):
    return -0.01 * S

S0 = 15
t = np.linspace(0, 20)

solution = odeint(model, S0, t)
salt_remaining = solution[-1][0]
rounded_salt = round(salt_remaining, 5)

print(f"The amount of salt remaining after 20 minutes is {rounded_salt} kg.")
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
To determine the initial current \( I(0) \) when the switch is closed in an RL circuit with \( R = 10 \, \Omega \) and \( L = 2 \, \text{H} \), we analyze the circuit behavior at \( t = 0 \).

1. **Kirchhoff's Voltage Law (KVL)**: The sum of voltages around the loop must be zero.
   \[
   V_L + V_R = V_{\text{source}}
   \]
   where \( V_L = L \frac{dI}{dt} \) and \( V_R = I R \).

2. **Initial Condition**: At \( t = 0 \), the current \( I(0) \) starts from zero because inductors oppose sudden changes in current. Therefore, \( I(0) = 0 \, \text{A} \).

3. **Voltage Distribution**: At \( t = 0 \), all the source voltage is across the inductor since \( V_R = 0 \). Thus, \( V_L = 20 \, \text{V} \).

4. **Current Rate of Change**: Using \( V_L = L \frac{dI}{dt} \), we find \( \frac{dI}{dt} = \frac{20}{2} = 10 \, \text{A/s} \). However, this is the rate of change, not the initial current.

Thus, the initial current \( I(0) \) is \( 0 \, \text{A} \).

```python
# Define the initial current
I_initial = 0.0

# Print the result rounded to 5 significant figures
print(round(I_initial, 5))
```
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

R = 10000          # Resistance in ohms
C = 5e-6           # Capacitance in farads
V_batt = 12        # Battery voltage in volts
V_target = 8       # Target voltage in volts

def dVdt(t, V):
    return (V_batt - V) / (R * C)

sol = solve_ivp(dVdt, t_span=(0, 1), y0=[0], dense_output=True, rtol=1e-9, atol=1e-12)

def voltage_difference(t):
    return sol.sol(t)[0] - V_target

result = root_scalar(voltage_difference, bracket=[0, 1], method='brentq')

print(f"{result.root:.5f}")
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import odeint
import numpy as np

def cooling_model(T, t, k, T_room):
    return -k * (T - T_room)

# Initial temperature
T0 = 200
T_room = 25

# Determine k using the temperature at t=10
T_at_10 = 150
t_10 = 10

# Calculate k
k = -np.log((T_at_10 - T_room) / (T0 - T_room)) / t_10

# Time points to solve for
t = np.linspace(0, 20)

# Solve ODE
sol = odeint(cooling_model, T0, t, args=(k, T_room))

# Get temperature at t=20
T_20 = sol[-1][0]

print(round(T_20, 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar
import numpy as np

# Calculate the rate constant k
k = -np.log(8000/10000) / 3

def model(t, P):
    return -k * P

# Initial population
P0 = 10000

# Time span for solving the ODE
t_span = (0, 20)

# Solve the ODE
sol = solve_ivp(model, t_span, [P0], dense_output=True)

# Function to find when population reaches 5000
def population_difference(t):
    return sol.sol(t)[0] - 5000

# Find the root
result = root_scalar(population_difference, bracket=[0, 20], method='brentq')

print(f"{result.root:.5f}")
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
import numpy as np

# Define the model
def rc_circuit(t, q):
    return -25 * q + 21250 * np.cos(150 * t)

# Initial condition
q0 = [-0.05]

# Time points
t_span = (0, 0.2)
t_eval = [0.2]

# Solve ODE
sol = solve_ivp(rc_circuit, t_span, q0, t_eval=t_eval)

# Extract and round the result
charge = round(sol.y[0][0], 5)
print(charge)
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
To solve the given RL circuit problem, we'll use the `odeint` solver in Python to numerically solve the differential equation governing the current over time.

```python
from scipy.integrate import odeint
import numpy as np

# Constants
R = 12  # Resistance in ohms
L = 4   # Inductance in henrys
E = lambda t: 60 * np.sin(30 * t)  # Voltage source

# Differential equation: dI/dt = (E(t) - R*I)/L
def dIdt(I, t):
    return (E(t) - R * I) / L

# Initial condition
I0 = 0

# Time points to solve for
t = np.linspace(0, 3, 100)

# Solve ODE
sol = odeint(dIdt, I0, t)

# Get the current at t=3
current_at_3 = sol[-1][0]

# Round to 5 decimal places
print(round(current_at_3, 5))
```
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
import numpy as np

# Constants
T_env = 75  # Ambient temperature (°F)
T0 = 185    # Initial temperature (°F)
t_span = (0, 45)  # Time span in minutes

# Calculate the cooling constant k using the data at t=30
T_at_30 = 150  # Temperature after 30 minutes
k = -np.log((T_at_30 - T_env) / (T0 - T_env)) / 30

def cooling_model(t, T):
    return -k * (T - T_env)

# Initial condition
T_initial = [T0]

# Solve the ODE
sol = solve_ivp(cooling_model, t_span, T_initial, t_eval=[45])

# Extract and print the result rounded to 5 significant figures
print(round(sol.y[0][0], 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

def model(t, N):
    k = np.log(2) / 20  # Continuous growth rate
    return k * N

def find_time():
    N0 = 60
    t_span = (0, 200)  # Sufficiently large time span
    sol = solve_ivp(model, t_span, [N0], dense_output=True)

    def voltage_difference(t):
        return sol.sol(t)[0] - 20000

    result = root_scalar(voltage_difference, bracket=[0, 200], method='brentq')
    return result.root

time_required = find_time()
print(f"{time_required:.5f}")
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
To solve the problem of determining the time required for an investment to grow from 100,000 kwanzas to 300,000 kwanzas (yielding a 200,000 kwanzas profit) with continuous compounding at a 4% annual interest rate, we can model this using an ordinary differential equation (ODE). The ODE describing continuous growth is:

\[ \frac{dA}{dt} = 0.04A \]

with the initial condition \( A(0) = 100,000 \). We need to find the time \( t \) when \( A(t) = 300,000 \).

### Approach:
1. **Model the Problem with an ODE**: The continuous growth of the investment can be described by the ODE \( \frac{dA}{dt} = 0.04A \), where \( A \) is the amount at time \( t \).
2. **Solve the ODE Numerically**: Use `solve_ivp` from SciPy to solve the ODE over a suitable interval and obtain a dense solution for interpolation.
3. **Find the Time When \( A(t) = 300,000 \)**: Define a function that computes the difference between \( A(t) \) and 300,000, then use `root_scalar` to find the root of this function, which gives the desired time.

### Solution Code:
```python
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

# Constants
A0 = 100000  # Initial amount in kwanzas
r = 0.04      # Annual interest rate
target_A = 300000  # Target amount

# Define the ODE
def dA_dt(t, A):
    return r * A

# Solve the ODE using solve_ivp with dense output for interpolation
sol = solve_ivp(dA_dt, (0, 50), [A0], dense_output=True, rtol=1e-9, atol=1e-12)

# Function to find the root where A(t) = target_A
def amount_difference(t):
    return sol.sol(t)[0] - target_A

# Find the time when the amount reaches target_A
result = root_scalar(amount_difference, bracket=[0, 50], method='brentq')

# Print the result rounded to 5 decimal places
print(f"{round(result.root, 5)}")
```

### Explanation:
1. **ODE Setup**: The ODE \( \frac{dA}{dt} = 0.04A \) models the continuous growth of the investment.
2. **Numerical Solution**: `solve_ivp` is used to solve the ODE over a time span from 0 to 50 years, providing a dense solution for accurate interpolation.
3. **Root Finding**: The `root_scalar` function finds the exact time when the amount reaches 300,000 kwanzas by solving \( A(t) - 300,000 = 0 \).

This approach ensures that we accurately determine the time required for the investment to reach the desired amount using numerical methods.
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
To solve the problem of determining the amount of salt in the tank after 10 minutes, we model the situation using a first-order linear ordinary differential equation (ODE). The ODE describes the rate of change of salt in the tank due to the inflow and outflow of brine. We then solve this ODE numerically using `solve_ivp` from SciPy.

**Problem Analysis:**
1. **Initial Condition:** At t=0, the tank contains 4 lb of salt.
2. **Rate of Change:** The net rate of change of salt is given by the difference between the inflow and outflow rates.
   - Inflow rate: 5 gal/min * 2 lb/gal = 10 lb/min.
   - Outflow rate: (5 gal/min) * (S(t)/100 lb/gal) = 0.05*S(t) lb/min.
3. **ODE:** dS/dt = 10 - 0.05*S(t).
4. **Solver:** Use `solve_ivp` to solve the ODE over the interval [0, 10] with the initial condition S(0) = 4.

```python
from scipy.integrate import solve_ivp
import numpy as np

# Define the model
def salt_model(t, S):
    return 10 - 0.05 * S

# Initial condition
S0 = 4

# Time span
t_span = (0, 10)

# Solve ODE
sol = solve_ivp(salt_model, t_span, [S0], t_eval=[10])

# Extract and round the result to 5 significant figures
result = round(sol.y[0][0], 5)
print(result)
```
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
import numpy as np

def model(t, N):
    return 0.5493 * N

N0 = [1000]
t_span = (0, 5)
sol = solve_ivp(model, t_span, N0, t_eval=[5])
print(round(sol.y[0][0], 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
import numpy as np

def model(t, S):
    return -0.01 * S

S0 = 25
t_span = (0, 30)
sol = solve_ivp(model, t_span, [S0], t_eval=[30])
print(round(sol.y[0][0], 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import odeint
import numpy as np

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

# Initial temperature
T0 = 300
# Surrounding temperature
T_env = 70
# Time points
t = np.linspace(0, 40, 1000)

# Calculate k using the given data at t=10
k = -np.log((250 - T_env) / (T0 - T_env)) / 10

# Solve ODE
sol = odeint(cooling, T0, t, args=(k, T_env))

# Get temperature at t=40
temperature = sol[-1][0]

# Round to 5 significant figures
rounded_temperature = round(temperature, 5)

print(rounded_temperature)
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
import numpy as np

def cooling_model(t, T, k, T_env):
    return -k * (T - T_env)

# Initial temperature
T0 = 400
# Ambient temperature
T_env = 75
# Time points
t_span = (0, 20)
# Calculate k using the given data at t=5
k = np.log((400 - T_env)/(350 - T_env)) / 5

# Solve ODE
sol = solve_ivp(cooling_model, t_span, [T0], args=(k, T_env), t_eval=[20])

# Extract and round the result
temperature = sol.y[0][0]
rounded_temperature = round(temperature, 5)
print(rounded_temperature)
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

def model(t, A):
    r = 0.05  # Continuous interest rate
    return r * A

A0 = 50000  # Initial investment
A_target = 150000  # Target amount

sol = solve_ivp(model, t_span=(0, 30), y0=[A0], dense_output=True)

def amount_difference(t):
    return sol.sol(t)[0] - A_target

result = root_scalar(amount_difference, bracket=[0, 30], method='brentq')

print(round(result.root, 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
To solve the problem, we model the system using two coupled ODEs for salt amount \( S(t) \) and volume \( V(t) \). The equations are:

\[
\frac{dS}{dt} = 0.6 - \frac{S}{V} \cdot 0.1\sqrt{V}
\]
\[
\frac{dV}{dt} = 2 - 0.1\sqrt{V}
\]

We solve these using `odeint` and evaluate \( S(30) \).

```python
from scipy.integrate import odeint
import numpy as np

def model(state, t):
    S, V = state
    dSdt = 0.6 - (S / V) * 0.1 * np.sqrt(V)
    dVdt = 2 - 0.1 * np.sqrt(V)
    return [dSdt, dVdt]

initial_state = [5, 100]
time = np.linspace(0, 30)

solution = odeint(model, initial_state, time)
salt_amount = solution[-1][0]

print(f"{salt_amount:.5f}")
```
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar
import numpy as np

# Given data
P0 = 5000  # Initial population
P_5 = 4000  # Population after 5 days
target = 2500  # Target population

# Calculate the rate constant k
k = np.log(P0 / P_5) / 5

# Define the ODE model
def model(t, P):
    return -k * P

# Solve the ODE
sol = solve_ivp(model, (0, 20), [P0], dense_output=True)

# Function to find when population reaches target
def find_target(t):
    return sol.sol(t)[0] - target

# Find the root
result = root_scalar(find_target, bracket=[0, 20], method='brentq')

# Print the result rounded to 5 decimal places
print(round(result.root, 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import solve_ivp
import numpy as np

def model(t, S):
    return 8 - (S / 50)

S0 = [30]
t_span = (0, 10)
sol = solve_ivp(model, t_span, S0, t_eval=[10])
print(round(sol.y[0][0], 5))
************
💾 Cache salvo após linha 20
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
The initial current I(0) is determined by the fact that an inductor's current cannot change instantaneously. At t=0, the current through the inductor is zero, so all the supply voltage is across the inductor, resulting in I(0) = 0.

```python
# Define the initial current
I_initial = 0

# Print the initial current
print("The initial current I(0) is", I_initial, "A")
```
************
✓ Cache usado para índice 21
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import odeint
import numpy as np

R = 10000  # Resistance in ohms
C = 2e-6   # Capacitance in microfarads
V_batt = 12  # Battery voltage in volts
t = np.linspace(0, 0.1, 100)  # Time span

def dQdt(Q, t):
    return (V_batt - Q/C) / R

Q0 = 0  # Initial charge
sol = odeint(dQdt, Q0, t)

charge = sol[-1][0]
print(round(charge, 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
from scipy.integrate import odeint
import numpy as np

# Constants
T_env = 20  # Room temperature (°C)
T0 = 90     # Initial temperature of coffee (°C)
t_data = 10  # Time when temperature is measured (minutes)
T_data = 70  # Temperature at t_data (°C)

# Calculate the cooling constant k
k = -np.log((T_data - T_env) / (T0 - T_env)) / t_data

# Define the cooling model
def cooling_model(T, t, k, T_env):
    return -k * (T - T_env)

# Time points where we want to solve the ODE
t = np.linspace(0, 20, 100)

# Solve ODE
sol = odeint(cooling_model, T0, t, args=(k, T_env))

# Get the temperature at t=20 minutes
temperature_at_20 = sol[-1][0]

# Round to 5 decimal places
print(round(temperature_at_20, 5))
************
Cache saved to disk.
************** deepseek/deepseek-r1-distill-llama-70b:free
To solve the problem of finding the half-life of a radioactive substance, we start by recognizing that the decay follows an exponential model. The given data allows us to determine the decay constant, which we then use to find the half-life.


==================================================================

In [ ]:
df.iloc['']

In [ ]:
import pandas as pd
import os
import re
import sympy as sp
import numpy as np
from scipy.integrate import solve_ivp, odeint
import sys
import contextlib
from io import StringIO

# === Configurações iniciais ===
#INPUT_CSV = '/content/drive/MyDrive/codigo_python/math_ODEsdataset_results.csv'
OUTPUT_CSV = '/content/drive/MyDrive/codigo_python/math_ODEsdataset_final_results.csv'

# === Ambiente simplificado para execução ===
# Mantemos apenas as funções essenciais para resolver EDOs
DEFAULT_GLOBALS = {
    'np': np,
    'sp': sp,
    'solve_ivp': solve_ivp,
    'odeint': odeint,
    'dsolve': sp.dsolve,
    'Eq': sp.Eq,
    'Function': sp.Function,
    'Symbol': sp.Symbol,
    'sin': sp.sin,
    'cos': sp.cos,
    'exp': sp.exp,
    'log': sp.log,
    'sqrt': sp.sqrt,
    'pi': sp.pi,
    'e': sp.E
}

# === Funções auxiliares ===
def extract_code(text):
    """Remove formatação Markdown do código"""
    if not isinstance(text, str):
        return ''
    return re.sub(r'```(python)?|```', '', text).strip()

@contextlib.contextmanager
def capture_stdout():
    """Captura saída impressa durante execução"""
    buffer = StringIO()
    original_stdout = sys.stdout
    sys.stdout = buffer
    try:
        yield buffer
    finally:
        sys.stdout = original_stdout

def execute_ode_code(code_str):
    """Executa código Python para soluções de EDOs"""
    try:
        local_vars = {}

        # Execução direta sem restrições excessivas
        with capture_stdout() as stdout:
            exec(code_str, DEFAULT_GLOBALS, local_vars)
        output = stdout.getvalue().strip()

        # Tenta extrair número da saída
        if output:
            try:
                return float(output)
            except ValueError:
                pass

        # Tenta encontrar resultado em variáveis de saída
        output_vars = ['result', 'solution', 'value', 'final_value', 'answer', 'output']
        for name in output_vars:
            if name in local_vars and isinstance(local_vars[name], (int, float)):
                return float(local_vars[name])

        # Tenta encontrar o último valor numérico
        for val in local_vars.values():
            if isinstance(val, (int, float)):
                return float(val)

        return None
    except Exception as e:
        print(f"Erro na execução: {str(e)[:100]}")
        return None

# === Carregar e processar o dataset ===
def process_dataset():
    # Carregar CSV
    try:
        df = pd.read_csv('/content/math_ODEsdataset_csv.txt_models')
        print(f"Dataset carregado: {len(df)} linhas")
    except FileNotFoundError:
        print(f"Erro: Arquivo não encontrado - {INPUT_CSV}")
        return

    # Identificar colunas com códigos
    code_columns = [col for col in df.columns if col.endswith('_class')]

    if not code_columns:
        print("Nenhuma coluna de código encontrada (_class)")
        return

    print(f"Colunas de código identificadas: {', '.join(code_columns)}")

    # Processar cada coluna de código
    for col in code_columns:
        result_col = col.replace('_class', '_exec_result')
        df[result_col] = 'not_executed'

        print(f"\n{'='*50}")
        print(f"Processando coluna: {col}")
        print(f"{'='*50}")

        for idx, row in df.iterrows():
            code_raw = row[col]

            if pd.isna(code_raw):
                df.at[idx, result_col] = 'no_code'
                continue


            code_clean = extract_code(str(code_raw))

            print(f'Code executing ({col}/{idx}):', code_clean, flush=True)

            if not code_clean:
                df.at[idx, result_col] = 'empty_code'
                continue

            # Executar código
            result = execute_ode_code(code_clean)

            if result is not None:
                df.at[idx, result_col] = round(result, 4)
            else:
                df.at[idx, result_col] = 'exec_error'

            # Mostrar progresso
            if (idx + 1) % 10 == 0:
                print(f"Processadas {idx+1}/{len(df)} linhas")

    # Salvar resultados
    os.makedirs('results', exist_ok=True)
    df.to_csv(OUTPUT_CSV, index=False)
    print(f"\n✅ Resultados salvos em: {OUTPUT_CSV}")

    return df

# === Execução principal ===
if __name__ == "__main__":
    print("Iniciando execução de códigos Python do dataset...")
    result_df = process_dataset()

    if result_df is not None:
        # Mostrar resumo estatístico
        print("\nResumo estatístico:")
        for col in result_df.columns:
            if col.endswith('_exec_result'):
                success_count = result_df[col].apply(lambda x: isinstance(x, float)).sum()
                error_count = len(result_df) - success_count
                print(f"{col}: {success_count} sucessos, {error_count} erros")

    print("Processamento concluído!")

Iniciando execução de códigos Python do dataset...
Dataset carregado: 50 linhas
Colunas de código identificadas: meta-llama/llama-3.1-405b-instruct:free_class, google/gemma-3-27b-it:free_class, deepseek/deepseek-r1-distill-llama-70b:free_class, mistralai/mistral-small-3.2-24b-instruct:free_class, x-ai/grok-3-mini-beta_class, google/gemini-2.5-pro-preview_class

==================================================
Processando coluna: meta-llama/llama-3.1-405b-instruct:free_class
==================================================
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/0): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.7944 * P

P0 = [2]
t_span = (0, 6)
sol = solve_ivp(model, t_span, P0, t_eval=[6])
print(round(sol.y[0][0], 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/1): from scipy.integrate import solve_ivp
import numpy as np

def model(t, S):
    return - (10/1000) * S

S0 = [15]
t_span = (0, 20)
sol = solve_ivp(model, t_span, S0, t_eval=[20])
print(round(sol.y[0][0], 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/2): import numpy as np
from scipy.integrate import solve_ivp

# Constants
R = 10  # Resistance in ohms
L = 2   # Inductance in henries
V = 20  # Voltage in volts

# Initial condition
I0 = 0  # Initial current in amperes

# Time span
t_span = (0, 0.01)  # Time span in seconds

# Differential equation
def dIdt(t, I):
    return (V - R * I) / L

# Solve the differential equation
sol = solve_ivp(dIdt, t_span, [I0], t_eval=[0])

# Print the initial current
print(round(sol.y[0][0], 5))
Erro na execução: name 'V' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/3): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

R = 10000          # Resistance in ohms
C = 5e-6           # Capacitance in farads
V_batt = 12        # Battery voltage in volts
V_target = 8       # Target voltage in volts

def dVdt(t, V):
    return (1 / (R * C)) * (V_batt - V)

sol = solve_ivp(dVdt, t_span=(0, 1), y0=[0], dense_output=True, rtol=1e-9, atol=1e-12)

def voltage_difference(t):
    return sol.sol(t)[0] - V_target

result = root_scalar(voltage_difference, bracket=[0, 1], method='brentq')

print(round(result.root, 5))
Erro na execução: name 'R' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/4): import numpy as np
from scipy.integrate import odeint

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

T_env = 25
T0 = 200
t1 = 10
T1 = 150

k = -np.log((T1 - T_env) / (T0 - T_env)) / t1  # calculate k from first data point

time = np.linspace(0, 20, 100)
sol = odeint(cooling, T0, time, args=(k, T_env))
T_20 = sol[-1][0]

print(round(T_20, 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/5): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def population_decrease(P, t, k):
    return -k * P

def residual(t):
    P0 = 10000
    k = -np.log(8000 / P0) / 3  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(population_decrease, P0, time, args=(k,))
    P_t = sol[-1][0]
    return P_t - 5000

sol = root_scalar(residual, bracket=(0, 50), method='bisect')

print(round(sol.root, 5))
Erro na execução: name 'population_decrease' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/6): import numpy as np
from scipy.integrate import odeint

# Constants
R = 10  # Resistance in ohms
C = 4e-3  # Capacitance in farads
E0 = 85  # Voltage amplitude in volts
w = 150  # Angular frequency in rad/s
q0 = -0.05  # Initial charge in coulombs

# Time points
t = np.array([0, 2])

# ODE function
def dqdt(q, t, R, C, E0, w):
    return (E0 * np.cos(w * t) - q / C) / R

# Solve ODE
sol = odeint(dqdt, q0, t, args=(R, C, E0, w))

# Print charge at t = 0, 2
print(np.round(sol, 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/7): import numpy as np
from scipy.integrate import odeint

# Constants
R = 12  # Resistance in ohms
L = 4   # Inductance in henries
E0 = 60  # Voltage amplitude in volts
w = 30  # Angular frequency

# ODE model: L*dI/dt + R*I = E0*sin(w*t)
def model(I, t):
    dIdt = (E0 * np.sin(w * t) - R * I) / L
    return dIdt

# Initial condition: I(0) = 0
I0 = 0

# Time points
t = np.linspace(0, 3, 1000)

# Solve ODE
sol = odeint(model, I0, t)

# Find current at t=3
I_3 = sol[-1][0]

print(round(I_3, 5))
Erro na execução: name 'E0' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/8): import numpy as np
from scipy.integrate import odeint

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def model(t, k):
    T_env = 75
    T0 = 185
    time = np.linspace(0, t, 100)
    sol = odeint(cooling, T0, time, args=(k, T_env))
    return sol[-1][0]

# calculate k from the data at t=30 min
k = -np.log((150 - 75) / (185 - 75)) / 0.5  # convert 30 min to hours

# calculate temperature after 45 min
t = 0.75  # convert 45 min to hours
T_45 = model(t, k)

print(round(T_45, 5))
Erro na execução: name 'cooling' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/9): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return np.log(2) / 20 * P

P0 = [60]
t_span = (0, 200)

def find_time(target):
    sol = solve_ivp(model, t_span, P0, dense_output=True)
    def residual(t):
        return sol.sol(t)[0] - target
    from scipy.optimize import root_scalar
    result = root_scalar(residual, bracket=[0, 200], method='brentq')
    return result.root

target = 20000
time_required = find_time(target)
print(round(time_required, 5))
Erro na execução: name 'model' is not defined
Processadas 10/50 linhas
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/10): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    r = 0.04  # interest rate
    return r * P

P0 = [100000]  # initial investment
t_span = (0, 100)  # time span

def profit(t):
    sol = solve_ivp(model, t_span, P0, t_eval=[t], rtol=1e-9, atol=1e-12)
    return sol.y[0][0] - 300000  # total amount - initial investment - desired profit

result = np.roots([0.04, -100000])  # solve exponential growth model directly
t = np.log(3) / 0.04  # solve for time directly

print(round(t, 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/11): from scipy.integrate import solve_ivp
import numpy as np

def model(t, y):
    return 10 - (5/100) * y

y0 = [4]
t_span = (0, 10)
sol = solve_ivp(model, t_span, y0, t_eval=[10])
print(round(sol.y[0][0], 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/12): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.5493 * P

P0 = [1000]
t_span = (0, 5)
t_eval = np.linspace(0, 5, 100)
sol = solve_ivp(model, t_span, P0, t_eval=t_eval)
print(round(sol.y[0][-1], 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/13): from scipy.integrate import solve_ivp
import numpy as np

def model(t, S):
    V = 500  # Volume of the tank in liters
    F = 5    # Flow rate in liters per minute
    return -F / V * S

S0 = [25]  # Initial amount of salt in kg
t_span = (0, 30)  # Time span in minutes
sol = solve_ivp(model, t_span, S0, t_eval=[30])
print(round(sol.y[0][0], 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/14): import numpy as np
from scipy.integrate import odeint

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

T_env = 70  # Room temperature in °F
T0 = 300  # Initial temperature in °F
T_10 = 250  # Temperature after 10 minutes in °F

# Calculate k from the data at t=10
k = -np.log((T_10 - T_env) / (T0 - T_env)) / 10

time = np.linspace(0, 40, 100)
sol = odeint(cooling, T0, time, args=(k, T_env))
T_40 = sol[-1][0]

print(round(T_40, 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/15): import numpy as np
from scipy.integrate import odeint

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def residual(k):
    T_env = 75
    T0 = 400
    time = np.linspace(0, 5, 100)
    sol = odeint(cooling, T0, time, args=(k, T_env))
    T_t = sol[-1][0]
    return T_t - 350

k = np.exp(-np.log((350 - 75) / (400 - 75)) / 5)  # calculate k from first data point
k = -np.log(k)/5

time = np.linspace(0, 20, 100)
sol = odeint(cooling, 400, time, args=(k, 75))
T_t = sol[-1][0]
print(round(T_t, 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/16): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    r = 0.05  # continuous interest rate
    return r * P

P0 = [50000]  # initial investment
t_span = (0, 100)  # time span in years

def find_time():
    for t_eval in np.arange(0, 100, 0.01):
        sol = solve_ivp(model, t_span, P0, t_eval=[t_eval])
        if round(sol.y[0][0], 2) >= 150000:
            return round(t_eval, 5)

print(find_time())
Erro na execução: name 'model' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/17): from scipy.integrate import solve_ivp
import numpy as np

# Initial conditions
V0 = 100  # Initial volume in liters
m0 = 5    # Initial salt amount in kg

# Parameters
Q_in = 2  # Inflow rate in L/min
c_in = 0.3  # Salt concentration in inflow (kg/L)
t_span = (0, 30)  # Time span in minutes

# ODEs
def model(t, y):
    V, m = y
    Q_out = 0.1 * np.sqrt(V)
    dVdt = Q_in - Q_out
    dmdt = Q_in * c_in - Q_out * (m / V)
    return [dVdt, dmdt]

# Solve ODEs
sol = solve_ivp(model, t_span, [V0, m0], t_eval=[30])

# Print salt amount after 30 minutes
print(round(sol.y[1][0], 5))
Erro na execução: name 'Q_in' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/18): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def population(P, t, k):
    return -k * P

def residual(t):
    P0 = 5000
    k = -np.log(4000 / P0) / 5  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(population, P0, time, args=(k,))
    P_t = sol[-1][0]
    return P_t - 2500

sol = root_scalar(residual, bracket=(0, 50), method='bisect')

print(round(sol.root, 5))
Erro na execução: name 'population' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/19): from scipy.integrate import solve_ivp
import numpy as np

def model(t, S):
    return 4 * 2 - (4/200) * S

S0 = [30]
t_span = (0, 10)
sol = solve_ivp(model, t_span, S0, t_eval=[10])
print(round(sol.y[0][0], 5))
Processadas 20/50 linhas
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/20): import numpy as np
from scipy.integrate import solve_ivp

# Define constants
R = 5  # Resistance in ohms
L = 1  # Inductance in henries
V = 10  # Voltage in volts

# Define the ODE
def dIdt(t, I):
    return (V - R * I) / L

# Initial condition
I0 = 0  # Initial current in amperes

# Solve the ODE
sol = solve_ivp(dIdt, t_span=(0, 0.01), y0=[I0], t_eval=[0])

# Print the initial current
print(round(sol.y[0][0], 5))
Erro na execução: name 'V' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/21): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def population(P, t, k):
    return -k * P

def residual(t):
    P0 = 5000
    k = -np.log(4000 / P0) / 5  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(population, P0, time, args=(k,))
    P_t = sol[-1][0]
    return P_t - 2500

sol = root_scalar(residual, bracket=(0, 50), method='bisect')

print(round(sol.root, 5))
Erro na execução: name 'population' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/22): from scipy.integrate import solve_ivp

R = 10000          # Resistance in ohms
C = 2e-6           # Capacitance in farads
V_batt = 12        # Battery voltage in volts

def dQdt(t, Q):
    return (1 / R) * (V_batt - Q / C)

sol = solve_ivp(dQdt, t_span=(0, 0.1), y0=[0], t_eval=[0.1])

print(round(sol.y[0][0], 5))
Erro na execução: name 'R' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/23): import numpy as np
from scipy.integrate import odeint

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

# Given data
T_env = 20  # Room temperature in °C
T0 = 90    # Initial coffee temperature in °C
T_10 = 70  # Coffee temperature after 10 minutes in °C
t_10 = 10  # Time in minutes

# Calculate k from the data at t=10
k = -np.log((T_10 - T_env) / (T0 - T_env)) / t_10

# Solve ODE for temperature after 20 minutes
time = np.linspace(0, 20, 100)
sol = odeint(cooling, T0, time, args=(k, T_env))
T_20 = sol[-1][0]

print(round(T_20, 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/24): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def decay(N, t, k):
    return -k * N

def residual(t):
    N0 = 100
    k = -np.log(60 / N0) / 10  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(decay, N0, time, args=(k,))
    N_t = sol[-1][0]
    return N_t - 50

sol = root_scalar(residual, bracket=(0, 50), method='bisect')

print(round(sol.root, 5))
Erro na execução: name 'decay' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/25): from scipy.integrate import solve_ivp
import numpy as np

L = 0.01  # Inductance in henries
R = 20    # Resistance in ohms
V = 100   # Voltage in volts

def di_dt(t, i):
    return (V - R * i) / L

i0 = [0]  # Initial current
t_span = (0, 0.01)
sol = solve_ivp(di_dt, t_span, i0, t_eval=[0.01])
print(round(sol.y[0][0], 5))
Erro na execução: name 'V' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/26): import numpy as np
from scipy.integrate import odeint

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

T_env = 70  # kitchen temperature
T0 = 350  # initial cake temperature
T_10 = 300  # cake temperature after 10 minutes

# calculate k from the data at t=10
k = -np.log((T_10 - T_env) / (T0 - T_env)) / 10

time = np.linspace(0, 20, 100)
sol = odeint(cooling, T0, time, args=(k, T_env))
T_20 = sol[-1][0]

print(round(T_20, 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/27): from scipy.integrate import solve_ivp
import numpy as np

def decay(t, A):
    return -0.10 * A

A0 = [200000]
t_span = (0, 10)
sol = solve_ivp(decay, t_span, A0, t_eval=[10])
print(round(sol.y[0][0], 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/28): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return np.log(2) / 0.5 * P

P0 = [100]
t_span = (0, 3)
sol = solve_ivp(model, t_span, P0, t_eval=[3])
print(round(sol.y[0][0], 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/29): from scipy.integrate import solve_ivp
import numpy as np

def decay(t, m):
    half_life = 12  # in days
    decay_rate = np.log(2) / half_life
    return -decay_rate * m

m0 = 1  # initial mass (arbitrary unit)
t_span = (0, 100)  # time span in days

sol = solve_ivp(decay, t_span, [m0], dense_output=True)

def mass_difference(t):
    target_mass = 0.1 * m0  # 10% of original mass
    return sol.sol(t)[0] - target_mass

from scipy.optimize import root_scalar
result = root_scalar(mass_difference, bracket=[0, 100], method='brentq')

print(round(result.root, 5))
Erro na execução: name 'm0' is not defined
Processadas 30/50 linhas
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/30): from scipy.integrate import solve_ivp
import numpy as np

# Initial amount of salt (in pounds) and water (in gallons)
salt_initial = 300
water_initial = 100

# Desired amount of salt (in pounds)
salt_desired = 200

# Flow rate (in gallons per minute)
flow_rate = 3

# Initial concentration of salt (in pounds per gallon)
concentration_initial = salt_initial / water_initial

# Desired concentration of salt (in pounds per gallon)
concentration_desired = salt_desired / water_initial

# Differential equation for the concentration of salt
def dCdt(t, C):
    return -flow_rate / water_initial * C

# Initial condition
C0 = [concentration_initial]

# Time span
t_span = (0, 100)

# Solve the differential equation
sol = solve_ivp(dCdt, t_span, C0, dense_output=True)

# Find the time when the concentration reaches the desired value
def concentration_difference(t):
    return sol.sol(t)[0] - concentration_desired

from scipy.optimize import root_scalar
result = root_scalar(concentration_difference, bracket=[0, 100], method='brentq')

print(round(result.root, 5))
Erro na execução: name 'flow_rate' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/31): from scipy.integrate import solve_ivp
import numpy as np

def model(t, A):
    return 0.04 * A

A0 = [1]
t_span = (0, 100)
sol = solve_ivp(model, t_span, A0, dense_output=True, rtol=1e-9, atol=1e-12)

def amount_difference(t):
    return sol.sol(t)[0] - 2

result = np.roots([0.04, -np.log(2)])[0]

print(round(result, 5))
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/32): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def residual(t):
    T_env = 60
    T0 = 180
    k = -np.log((120 - T_env) / (T0 - T_env))  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(cooling, T0, time, args=(k, T_env))
    T_t = sol[-1][0]
    return T_t - 90

sol = root_scalar(residual, bracket=(0, 10), method='bisect')

print(round(sol.root, 5))
Erro na execução: name 'cooling' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/33): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def residual(T_env):
    T0 = 70
    t1 = 5
    t2 = 10
    T1 = 60
    T2 = 55
    time1 = np.linspace(0, t1, 100)
    time2 = np.linspace(0, t2, 100)
    k1 = -np.log((T1 - T_env) / (T0 - T_env)) / t1
    k2 = -np.log((T2 - T_env) / (T0 - T_env)) / t2
    sol1 = odeint(cooling, T0, time1, args=(k1, T_env))
    sol2 = odeint(cooling, T0, time2, args=(k2, T_env))
    T_t1 = sol1[-1][0]
    T_t2 = sol2[-1][0]
    return (T_t1 - T1)**2 + (T_t2 - T2)**2

sol = root_scalar(residual, bracket=(0, 70), method='brentq')

print(round(sol.root, 5))
Erro na execução: name 'cooling' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/34): from scipy.integrate import solve_ivp
import numpy as np

# Initial number of radioactive nuclei (arbitrary value, as only the ratio matters)
N0 = 100

# Half-life
t_half = 1500

# Decay constant (calculated from half-life)
k = np.log(2) / t_half

# Time points to evaluate the solution
t_eval = [4500]

# Define the model
def decay(t, N):
    return -k * N

# Solve the ODE
sol = solve_ivp(decay, t_span=(0, 4500), y0=[N0], t_eval=t_eval)

# Calculate the percentage of remaining nuclei
remaining_percent = (sol.y[0][0] / N0) * 100

print(round(remaining_percent, 5))
Erro na execução: name 'k' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/35): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.005776 * P

P0 = [30000]
t_span = (0, 20)
sol = solve_ivp(model, t_span, P0, t_eval=[20])
k = 0.005776  # calculate k from first data point

def model2030(t, P):
    return k * P

P020 = [35000]
t_span2030 = (0, 10)
sol2030 = solve_ivp(model2030, t_span2030, P020, t_eval=[10])

print(round(sol2030.y[0][0], 5))
Erro na execução: name 'k' is not defined
Code executing (meta-llama/llama-3.1-405b-instruct:free_class/36): from scipy.integrate import solve_ivp
import numpy as np

def decay(t, A):
    return -0.05 * A

A0 = [1000000]
t_span = (0, 100)
sol = solve_ivp(decay, t_span, A0, dense_output=True, rtol=1e-9, atol=1e-12)

def amount_difference(t):
    return sol.sol(t)[0] - 250000

result = np.roots([1, -np.log(0.25)/np.log(0.95)])
print(round(result[0], 5))

<string>:19: ODEintWarning: Excess work done on this call (perhaps wrong Dfun type). Run with full_output = 1 to get quantitative information.

A saída de streaming foi truncada nas últimas 5000 linhas.
# Solve the ODE
sol = odeint(cooling, T0, t, args=(k, T_env))

# Extract the temperature at t=20 minutes
T_20 = sol[-1][0]

print(round(T_20, 5))
Code executing (google/gemma-3-27b-it:free_class/24): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def decay(A, t, k):
    return -k * A

def residual(t):
    A0 = 100
    k = -np.log(60 / A0) / 10
    A_t = A0 * np.exp(-k * t)
    return A_t - 50

sol = root_scalar(residual, bracket=(0, 20), method='bisect')

print(round(sol.root, 5))
Code executing (google/gemma-3-27b-it:free_class/25): from scipy.integrate import solve_ivp
import numpy as np

L = 0.01  # Inductance in Henries
R = 20  # Resistance in Ohms
V = 100  # Voltage in Volts

def dIdt(t, I):
    return (V - R * I) / L

I0 = [0]  # Initial current is 0
t_span = (0, 0.01)
sol = solve_ivp(dIdt, t_span, I0, dense_output=True)

print(round(sol.y[0][0], 5))
Erro na execução: name 'V' is not defined
Code executing (google/gemma-3-27b-it:free_class/26): is dT/dt = -k(T - T_env)
Here T_env = 60°C (constant medium temperature)
Initial temperature T(0) = 20°C
After 5 min, T(5) = 30°C
Find time t when T(t) = 40°C
Step 2:
- Calculate k from the data at t=5
- Define a residual function for temperature difference at time t
- Use root finding to get t when temperature reaches 40°C


</think> (Output-Solution)
import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def residual(t):
    T_env = 60
    T0 = 20
    k = -np.log((30 - T_env) / (T0 - T_env)) / 5  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(cooling, T0, time, args=(k, T_env))
    T_t = sol[-1][0]
    return T_t - 40

sol = root_scalar(residual, bracket=(0, 50), method='bisect')

print(round(sol.root, 5))
Erro na execução: invalid character '°' (U+00B0) (<string>, line 2)
Code executing (google/gemma-3-27b-it:free_class/27): from scipy.integrate import solve_ivp
import numpy as np

def model(t, A):
    return -0.10 * A

A0 = [200000]
t_span = (0, 10)
sol = solve_ivp(model, t_span, A0, t_eval=[10])
print(round(sol.y[0][0], 5))
Code executing (google/gemma-3-27b-it:free_class/28): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.0231049 * P

P0 = [100]
t_span = (0, 180)
sol = solve_ivp(model, t_span, P0, t_eval=[180])
print(round(sol.y[0][0], 5))
Code executing (google/gemma-3-27b-it:free_class/29): from scipy.integrate import solve_ivp
import numpy as np

def decay(t, y):
    return -0.05776 * y

y0 = [1]
t_span = (0, 100)
sol = solve_ivp(decay, t_span, y0, dense_output=True)

def residual(t):
    return sol.sol(t)[0] - 0.1

result = root_scalar(residual, bracket=[0, 100], method='brentq')

print(round(result.root, 5))
Erro na execução: name 'root_scalar' is not defined
Processadas 30/50 linhas
Code executing (google/gemma-3-27b-it:free_class/30): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar
import numpy as np

def salt_balance(t, y, rate_out, rate_in, volume):
    """
    Describes the rate of change of salt in the tank.

    Args:
        t: Time (not used in this autonomous equation).
        y: Amount of salt in the tank at time t.
        rate_out: Rate of outflow (gal/min).
        rate_in: Rate of inflow (gal/min).
        volume: Volume of the tank (gal).

    Returns:
        The rate of change of salt (lbs/min).
    """
    return (rate_in * 0 - rate_out * y / volume)

# Parameters
volume = 100  # gallons
rate_out = 3  # gallons/min
rate_in = 3  # gallons/min
initial_salt = 300  # pounds
desired_salt = 200  # pounds

# Define a residual function to find the time when the salt amount reaches the desired level
def residual(t):
    sol = solve_ivp(salt_balance, [0, t], [initial_salt], args=(rate_out, rate_in, volume), dense_output=True)
    salt_at_t = sol.sol(t)[0]
    return salt_at_t - desired_salt

# Use a root-finding algorithm to find the time when the salt amount is equal to the desired amount
result = root_scalar(residual, bracket=[0, 100], method='brentq')

# Print the result rounded to 5 decimal places
print(round(result.root, 5))
Erro na execução: name 'salt_balance' is not defined
Code executing (google/gemma-3-27b-it:free_class/31): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar
import numpy as np

def model(t, A):
    r = 0.04
    return r * A

A0 = [1]
t_span = (0, 100)  # Set a reasonable time span
sol = solve_ivp(model, t_span, A0, dense_output=True)

def residual(t):
    return sol.sol(t)[0] - 2

result = root_scalar(residual, bracket=[0, 100], method='brentq')
print(round(result.root, 5))
Erro na execução: name 'sol' is not defined
Code executing (google/gemma-3-27b-it:free_class/32): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def residual(t):
    T_env = 60
    T0 = 180
    k = -np.log((120 - T_env) / (T0 - T_env)) / 1  # calculate k from first data point
    time = np.linspace(0, t, 100)
    sol = odeint(cooling, T0, time, args=(k, T_env))
    T_t = sol[-1][0]
    return T_t - 90

sol = root_scalar(residual, bracket=(0, 50), method='bisect')

print(round(sol.root, 5))
Erro na execução: name 'cooling' is not defined
Code executing (google/gemma-3-27b-it:free_class/33): import numpy as np
from scipy.integrate import odeint
from scipy.optimize import root_scalar

def cooling(T, t, k, T_env):
    return -k * (T - T_env)

def residual(T_env):
    T0 = 70
    t1 = 5
    T1 = 60
    t2 = 10
    T2 = 55

    def solve_for_k(T_env):
        def ode_func(T, t):
            return -k * (T - T_env)

        k = -np.log((T1 - T_env) / (T0 - T_env)) / t1
        sol = odeint(ode_func, T0, np.linspace(0, t2, 100), args=(k, T_env))
        return sol[-1][0] - T2

    k_initial_guess = 0.01

    result = root_scalar(solve_for_k, bracket=(0, 100), method='brentq')

    return result.root

T_env = root_scalar(residual, bracket=(0, 70), method='brentq').root
print(round(T_env, 5))
Erro na execução: name 'root_scalar' is not defined
Code executing (google/gemma-3-27b-it:free_class/34): from scipy.integrate import solve_ivp
import numpy as np

def model(t, N):
    k = np.log(2) / 1500
    return -k * N

N0 = [1]
t_span = (0, 4500)
sol = solve_ivp(model, t_span, N0, t_eval=[4500])
print(round(sol.y[0][0] * 100, 5))
Code executing (google/gemma-3-27b-it:free_class/35): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P, k):
    return k * P

# Initial condition: P(0) = 30000 (population in 2010)
# P(10) = 35000 (population in 2020, 10 years after 2010)

# Find k using the data at t=10
# P(10) = P(0) * exp(k * 10)
# 35000 = 30000 * exp(10k)
# 7/6 = exp(10k)
# ln(7/6) = 10k
# k = ln(7/6) / 10
k = np.log(7/6) / 10

# Solve the ODE from t=0 to t=20 (2030 - 2010)
t_span = (0, 20)
P0 = [30000]
sol = solve_ivp(model, t_span, P0, args=(k,), t_eval=[20])

print(round(sol.y[0][0], 5))
Code executing (google/gemma-3-27b-it:free_class/36): from scipy.integrate import solve_ivp
import numpy as np
from scipy.optimize import root_scalar

def model(t, A):
    return -0.05 * A

def residual(t):
    A0 = 1000000
    sol = solve_ivp(model, (0, t), [A0], dense_output=True)
    return sol.y[0][-1] - 250000

sol = root_scalar(residual, bracket=[0, 50], method='brentq')
print(round(sol.root, 5))
Erro na execução: name 'model' is not defined
Code executing (google/gemma-3-27b-it:free_class/37): from scipy.integrate import solve_ivp
import numpy as np

def model_closed(t, v):
    g = 32.2  # Acceleration due to gravity in ft/s^2
    k = 0.5
    return g - k * v

def model_open(t, v):
    g = 32.2
    k = 10
    return g - k * v

def solve_problem():
    # Closed parachute phase (0 to 10 seconds)
    sol_closed = solve_ivp(model_closed, (0, 10), [0], dense_output=True)
    v_10 = sol_closed.sol(10)[0]

    # Open parachute phase (10 to 15 seconds)
    sol_open = solve_ivp(model_open, (10, 15), [v_10], dense_output=True)
    v_15 = sol_open.sol(15)[0]

    return v_15

result = solve_problem()
print(round(result, 5))
Erro na execução: name 'model_closed' is not defined
Code executing (google/gemma-3-27b-it:free_class/38): import numpy as np
from scipy.optimize import root_scalar

def equation(r):
    return np.exp(20 * r) - 3

sol = root_scalar(equation, bracket=[0, 1], method='brentq')
print(round(sol.root, 5))
Code executing (google/gemma-3-27b-it:free_class/39): from scipy.integrate import solve_ivp
import numpy as np

def model(t, x, c1, c2):
    k = 0.007389
    return -k * x * (c1 - c2)

c1 = 0.4  # Saturated concentration
c2 = 0.0  # Initial concentration
x0 = 10  # Initial amount undissolved
t_span = (0, 90)
sol = solve_ivp(model, t_span, [x0], args=(c1, c2), dense_output=True, t_eval=[90])
x_90 = sol.y[0][0]
if x_90 < 5:
    k = -np.log(5/10) / 90
else:
    k = 0.007389

t_span = (0, 180)
sol = solve_ivp(model, t_span, [x0], args=(c1, c2), dense_output=True, t_eval=[180])
x_180 = sol.y[0][0]
dissolved_amount = 10 - x_180
print(round(dissolved_amount, 5))
Processadas 40/50 linhas
Code executing (google/gemma-3-27b-it:free_class/40): from scipy.integrate import solve_ivp
import numpy as np

def circuit(t, i):
    L = 0.5
    R = 10
    V = 12
    return (V - R * i) / L

i0 = [0]
t_span = (0, 2)
sol = solve_ivp(circuit, t_span, i0, t_eval=[2])
print(round(sol.y[0][0], 5))
Code executing (google/gemma-3-27b-it:free_class/41): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return -k * P

# Given data
P_2010 = 60000
P_2020 = 40000
t_2010 = 0
t_2020 = 10

# Calculate k using the given data
def residual(k):
    sol = solve_ivp(model, (t_2010, t_2020), [P_2010], dense_output=True, t_eval=[t_2020])
    return sol.y[0][0] - P_2020

from scipy.optimize import root_scalar
sol = root_scalar(residual, bracket=(0, 1), method='brentq')
k = sol.root

# Solve for the population in 2030 (t = 20)
t_2030 = 20
sol = solve_ivp(model, (t_2010, t_2030), [P_2010], dense_output=True, t_eval=[t_2030])
population_2030 = sol.y[0][0]

print(round(population_2030, 5))
Erro na execução: name 'model' is not defined
Code executing (google/gemma-3-27b-it:free_class/42): from scipy.integrate import solve_ivp
import numpy as np

def model(t, y):
    V = 10000  # Volume of the room in cubic feet
    r = 5000 / V  # Rate of air exchange
    y_in = 0.0005  # Carbon dioxide concentration in incoming air
    return r * (y_in - y)

y0 = 0.0015  # Initial carbon dioxide concentration
t_span = (0, 3)  # Time interval in minutes
sol = solve_ivp(model, t_span, [y0], dense_output=True, t_eval=[3])
print(round(sol.y[0][0] * 100, 5))
Code executing (google/gemma-3-27b-it:free_class/43): from scipy.integrate import solve_ivp
import numpy as np

def model(t, v):
    g = 32.2  # gravitational acceleration in ft/s^2
    return (g - 2 * v) / 8

v0 = [0]
t_span = (0, 10)
sol = solve_ivp(model, t_span, v0, t_eval=[10])
print(round(sol.y[0][0], 5))
Code executing (google/gemma-3-27b-it:free_class/44): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar
import numpy as np

def moisture_loss(M, t, k):
    return -k * M

def residual(t):
    M0 = 1.0  # Initial moisture content (normalized)
    k = np.log(2) / 30  # Calculate k from the given information
    t_span = (0, t)
    sol = solve_ivp(moisture_loss, t_span, [M0], dense_output=True, args=(k,))
    M_t = sol.y[0][-1]
    return M_t - 0.05  # 5% remaining moisture content (1 - 0.95)

sol = root_scalar(residual, bracket=[0, 100], method='bisect')
print(round(sol.root, 5))
Erro na execução: name 'moisture_loss' is not defined
Code executing (google/gemma-3-27b-it:free_class/45): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

R = 15000          # Resistance in ohms
C = 3e-6           # Capacitance in farads
V_batt = 24        # Battery voltage in volts
V_target = 6      # Target voltage in volts

def dVdt(t, V):
    return (1 / (R * C)) * (V_batt - V)

sol = solve_ivp(dVdt, t_span=(0, 1), y0=[0], dense_output=True, rtol=1e-9, atol=1e-12)

def voltage_difference(t):
    return sol.sol(t)[0] - V_target

result = root_scalar(voltage_difference, bracket=[0, 1], method='brentq')

print(f"{result.root:.5f}")
Erro na execução: name 'R' is not defined
Code executing (google/gemma-3-27b-it:free_class/46): from scipy.integrate import solve_ivp
import numpy as np

def model(t, v):
    g = 32.2  # Acceleration due to gravity (ft/s^2)
    theta = np.radians(30)  # Angle of inclination in radians
    mu = 0.4  # Coefficient of friction
    m = 50 / g  # Mass of the block (slugs)

    # Net force acting on the block: F = mg*sin(theta) - mu*mg*cos(theta)
    # Acceleration: a = F/m = g*sin(theta) - mu*g*cos(theta)
    a = g * (np.sin(theta) - mu * np.cos(theta))
    return a

v0 = [0]  # Initial velocity (0 ft/s)
t_span = (0, 4)  # Time interval (0 to 4 seconds)
sol = solve_ivp(model, t_span, v0, dense_output=True)

velocity_at_4s = sol.sol(4)[0]
print(round(velocity_at_4s, 5))
Code executing (google/gemma-3-27b-it:free_class/47): from scipy.integrate import solve_ivp
import numpy as np

def model(t, v):
    return (20 - (7/4) * v) / 480

v0 = [18]
t_span = (0, 30)
sol = solve_ivp(model, t_span, v0, t_eval=[30])
print(round(sol.y[0][0], 5))
Code executing (google/gemma-3-27b-it:free_class/48): from scipy.integrate import solve_ivp
import numpy as np

def model(t, v):
    return (10 - 2 * v) / 64

v0 = [0]
t_span = (0, 5)
sol = solve_ivp(model, t_span, v0, t_eval=[5])
print(round(sol.y[0][0], 5))
Code executing (google/gemma-3-27b-it:free_class/49): from scipy.integrate import solve_ivp
import numpy as np

def model(t, A):
    return -0.10 * A

A0 = [15000000]
t_span = (0, 5)
sol = solve_ivp(model, t_span, A0, t_eval=[5])
print(round(sol.y[0][0], 5))
Processadas 50/50 linhas

==================================================
Processando coluna: deepseek/deepseek-r1-distill-llama-70b:free_class
==================================================
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/0): from scipy.integrate import solve_ivp
import numpy as np

def model(t, P):
    return 0.7944 * P

P0 = [2]
t_span = (0, 6)
sol = solve_ivp(model, t_span, P0, t_eval=[6])
print(round(sol.y[0][0], 5))
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/1): from scipy.integrate import odeint
import numpy as np

def model(S, t):
    return -0.01 * S

S0 = 15
t = np.linspace(0, 20)

solution = odeint(model, S0, t)
salt_remaining = solution[-1][0]
rounded_salt = round(salt_remaining, 5)

print(f"The amount of salt remaining after 20 minutes is {rounded_salt} kg.")
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/2): To determine the initial current \( I(0) \) when the switch is closed in an RL circuit with \( R = 10 \, \Omega \) and \( L = 2 \, \text{H} \), we analyze the circuit behavior at \( t = 0 \).

1. **Kirchhoff's Voltage Law (KVL)**: The sum of voltages around the loop must be zero.
   \[
   V_L + V_R = V_{\text{source}}
   \]
   where \( V_L = L \frac{dI}{dt} \) and \( V_R = I R \).

2. **Initial Condition**: At \( t = 0 \), the current \( I(0) \) starts from zero because inductors oppose sudden changes in current. Therefore, \( I(0) = 0 \, \text{A} \).

3. **Voltage Distribution**: At \( t = 0 \), all the source voltage is across the inductor since \( V_R = 0 \). Thus, \( V_L = 20 \, \text{V} \).

4. **Current Rate of Change**: Using \( V_L = L \frac{dI}{dt} \), we find \( \frac{dI}{dt} = \frac{20}{2} = 10 \, \text{A/s} \). However, this is the rate of change, not the initial current.

Thus, the initial current \( I(0) \) is \( 0 \, \text{A} \).


# Define the initial current
I_initial = 0.0

# Print the result rounded to 5 significant figures
print(round(I_initial, 5))
Erro na execução: unexpected character after line continuation character (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/3): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar

R = 10000          # Resistance in ohms
C = 5e-6           # Capacitance in farads
V_batt = 12        # Battery voltage in volts
V_target = 8       # Target voltage in volts

def dVdt(t, V):
    return (V_batt - V) / (R * C)

sol = solve_ivp(dVdt, t_span=(0, 1), y0=[0], dense_output=True, rtol=1e-9, atol=1e-12)

def voltage_difference(t):
    return sol.sol(t)[0] - V_target

result = root_scalar(voltage_difference, bracket=[0, 1], method='brentq')

print(f"{result.root:.5f}")
Erro na execução: name 'V_batt' is not defined
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/4): from scipy.integrate import odeint
import numpy as np

def cooling_model(T, t, k, T_room):
    return -k * (T - T_room)

# Initial temperature
T0 = 200
T_room = 25

# Determine k using the temperature at t=10
T_at_10 = 150
t_10 = 10

# Calculate k
k = -np.log((T_at_10 - T_room) / (T0 - T_room)) / t_10

# Time points to solve for
t = np.linspace(0, 20)

# Solve ODE
sol = odeint(cooling_model, T0, t, args=(k, T_room))

# Get temperature at t=20
T_20 = sol[-1][0]

print(round(T_20, 5))
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/5): from scipy.integrate import solve_ivp
from scipy.optimize import root_scalar
import numpy as np

# Calculate the rate constant k
k = -np.log(8000/10000) / 3

def model(t, P):
    return -k * P

# Initial population
P0 = 10000

# Time span for solving the ODE
t_span = (0, 20)

# Solve the ODE
sol = solve_ivp(model, t_span, [P0], dense_output=True)

# Function to find when population reaches 5000
def population_difference(t):
    return sol.sol(t)[0] - 5000

# Find the root
result = root_scalar(population_difference, bracket=[0, 20], method='brentq')

print(f"{result.root:.5f}")
Erro na execução: name 'k' is not defined
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/6): from scipy.integrate import solve_ivp
import numpy as np

# Define the model
def rc_circuit(t, q):
    return -25 * q + 21250 * np.cos(150 * t)

# Initial condition
q0 = [-0.05]

# Time points
t_span = (0, 0.2)
t_eval = [0.2]

# Solve ODE
sol = solve_ivp(rc_circuit, t_span, q0, t_eval=t_eval)

# Extract and round the result
charge = round(sol.y[0][0], 5)
print(charge)
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/7): To solve the given RL circuit problem, we'll use the `odeint` solver in Python to numerically solve the differential equation governing the current over time.


from scipy.integrate import odeint
import numpy as np

# Constants
R = 12  # Resistance in ohms
L = 4   # Inductance in henrys
E = lambda t: 60 * np.sin(30 * t)  # Voltage source

# Differential equation: dI/dt = (E(t) - R*I)/L
def dIdt(I, t):
    return (E(t) - R * I) / L

# Initial condition
I0 = 0

# Time points to solve for
t = np.linspace(0, 3, 100)

# Solve ODE
sol = odeint(dIdt, I0, t)

# Get the current at t=3
current_at_3 = sol[-1][0]

# Round to 5 decimal places
print(round(current_at_3, 5))
Erro na execução: unterminated string literal (detected at line 1) (<string>, line 1)
Code executing (deepseek/deepseek-r1-distill-llama-70b:free_class/8): from scipy.integrate import solve_ivp
import numpy as np

# Constants
T_env = 75  # Ambient temperature (°F)
T0 = 185    # Initial temperature (°F)
t_span = (0, 45)  # Time span in minutes

# Calculate the cooling constant k using the data at t=30
T_at_30 = 150  # Temperature after 30 minutes
k = -np.log((T_at_30 - T_env) / (T0 - T_env)) / 30

def cooling_model(t, T):
    return -k * (T - T_env)

# Initial condition
T_initial = [T0]

# Solve the ODE
sol = solve_ivp(cooling_model, t_span, T_initial, t_eval=[45])

# Extract and print the result rounded to 5 significant figures
print(round(sol.y[0][0], 5))
Erro na execução: name 'k' is not defined

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/codigo_python/math_ODEsdataset_final_results.csv')

In [ ]:
df

,Index,Question,Proposed Solution,Answer,meta-llama/llama-3.1-405b-instruct:free_class,google/gemma-3-27b-it:free_class,deepseek/deepseek-r1-distill-llama-70b:free_class,mistralai/mistral-small-3.2-24b-instruct:free_class,x-ai/grok-3-mini-beta_class,google/gemini-2.5-pro-preview_class,meta-llama/llama-3.1-405b-instruct:free_exec_result,google/gemma-3-27b-it:free_exec_result,deepseek/deepseek-r1-distill-llama-70b:free_exec_result,mistralai/mistral-small-3.2-24b-instruct:free_exec_result,x-ai/grok-3-mini-beta_exec_result,google/gemini-2.5-pro-preview_exec_result
0,0,A population of protozoa grows at a constant r...,"We have dP/dt = kP Therefore dP/dt = 0,7944P ...",2.350000e+02,```python\nfrom scipy.integrate import solve_i...,".y[0][0], 4))\n===============================...",from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\n\ndef m...,from scipy.integrate import solve_ivp\n\ndef m...,```python\nfrom scipy.integrate import solve_i...,234.9685,exec_error,234.9685,234.9685,234.9685,234.9685
1,1,A tank contains 1000 L of salt water with 15 k...,Let S(t) be the amount of salt (in kilograms...,1.230000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import odeint\nimport num...,from scipy.integrate import solve_ivp\n\ndef s...,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,12.281,12.281,15.0,12.281,12.281,12.281
2,2,A resistor R=10Ω and an inductor L=2H are conn...,"Using Kirchhoff's Voltage Law KVL, the sum of ...",0.000000e+00,```python\nimport numpy as np\nfrom scipy.inte...,is V(t) = V_batt * (1 - e^(-t/(RC)))\n# Step 2...,To determine the initial current \( I(0) \) wh...,from scipy.integrate import solve_ivp\n\nR = 1...,from scipy.integrate import solve_ivp\n\ndef m...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,0.0,exec_error
3,3,A 5μF capacitor is charged through a 10kΩ resi...,"In an RC charging circuit, Kirchhoff's voltag...",5.490000e-02,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nfrom scipy.integrate import solve_i...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
4,4,An object is removed from an oven at 200°C and...,Let T(t) represent the temperature of the obje...,1.141900e+02,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import odeint\nimport num...,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,114.2857,210.0942,114.2857,114.2857,exec_error,114.2886
5,5,A certain village in Angola had a population ...,Let P(t) be the population at time t. The rate...,9.260000e+00,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,from scipy.integrate import odeint\nfrom scipy...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
6,6,"Find the charge when t=0,2, in a series RC cir...","We have Rdq(t)/dt+1/C q=V Since R=10, C=4*10^(...",-5.290000e-02,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nimport ...,Here's the Python code that solves the problem...,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,10.0,exec_error,-132.7955,exec_error,exec_error,-0.0534
7,7,A resistor R=12Ω and an inductor L=4H are conn...,"Using Kirchhoff's Voltage Law (KVL), the sum o...",2.660000e-01,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,"To solve the given RL circuit problem, we'll u...",from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,0.2662,exec_error,0.2662,0.2662,0.2662
8,8,A roast chicken is removed from the oven when ...,Let T(t) represent the temperature of the roas...,1.364000e+02,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import odeint\nfrom scipy...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
9,9,"Escherichia coli, a common bacteria found in t...","We have dP/dt = kP. Integrating both sides, we...",1.676300e+02,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,from scipy.integrate import solve_ivp\nfrom sc...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
10,10,"Suppose an amount of 100,000 kwanzas is invest...","We have dA/dt = kA Therefore dA/dt = 0,04A → ...",1.730000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,To solve the problem of determining the time r...,from scipy.integrate import solve_ivp\nfrom sc...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,27.4653,exec_error,exec_error,exec_error,exec_error,exec_error
11,11,"At time t = 0, a tank contains 4 lb of salt di...",Let y(t) be the amount of salt (in pounds) aft...,8.110000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,To solve the problem of determining the amount...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,81.1196,81.1196,exec_error,81.1196,81.12,81.1196
12,12,A bacterial culture grows at a rate proportion...,dP/dt = kP → P(t) = P0e^(kt) Given P(0)=1000 ...,1.558800e+04,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,15588.5321,15589.011,15588.5321,exec_error,exec_error,15589.0
13,13,A tank contains 500L of brine with 25kg salt. ...,dS/dt=−5S/500=−S/100 S(t)=25e^(-t/100) S(30)=...,1.853000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import odeint\...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\n\ndef s...,from scipy.integrate import solve_ivp\n\ndef m...,```python\nfrom scipy.integrate import solve_i...,18.5205,18.5205,18.5205,18.5205,18.5205,18.5205
14,14,A hot metal cools from 300°F to 250°F in 10 mi...,T(t)=70+230e^(-kt) At t=10: 250=70+230e^(-10k...,1.944100e+02,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import odeint\...,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```\nimport numpy as np\nfrom scipy.integrate ...,```python\nimport numpy as np\nfrom scipy.inte...,156.2793,exec_error,156.2793,156.2793,exec_error,156.2808
15,15,A pizza cools from 400°F to 350°F in 5 minutes...,T(t)=75+325e^(-kt) At t=5: 350=75+325e^(-5k)→...,2.937300e+02,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import odeint\...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,446.4701,241.6022,241.6072,241.6022,exec_error,241.6072
16,16,"An amount of 50,000 dollar is invested at 5 p...","150,000=50.000e^(0.05t)→ t=ln(3)/0.05≈21.97 y...",2.197000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,21.971
17,17,A tank contains 100L of water with 5kg salt. B...,Volume changes as dV/dt = 2 - 0.1sqrt(V) Salt...,2.814000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,"To solve the problem, we model the system usin...",```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,19.5226,exec_error,19.5108,19.5108,19.5108
18,18,A population of insects decreases at a rate pr...,"P(t) = 5000e^(-kt), use P(5) = 4000 to find k...",1.550000e+01,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,from scipy.integrate import odeint\nfrom scipy...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
19,19,A tank contains 200 liters of salt water with ...,Let S(t) be the amount of salt (in grams) at t...,9.130000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\n\ndef s...,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,97.0696,97.0696,97.0696,97.0696,97.0696,97.0696
20,20,A resistor R=5Ω and an inductor L=1H are conne...,KVL gives: L dI/dt + RI = V → dI/dt + 5I = 1...,0.000000e+00,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,The initial current I(0) is determined by the ...,from scipy.integrate import solve_ivp\n\nR = 5...,from scipy.integrate import solve_ivp\n\ndef m...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,0.0,exec_error,exec_error,0.0,0.0
21,21,A population of insects decreases at a rate pr...,dP/dt = -kP → P(t) = P0e^(-kt) Given P(0) =...,1.550000e+01,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,from scipy.integrate import odeint\nfrom scipy...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
22,22,"In an RC circuit with R = 10kΩ and C = 2μ F , ...",Charge on capacitor: q(t) = CV(1 - e^(-t/RC)...,2.398000e-05,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import odeint\nimport num...,from scipy.integrate import solve_ivp\n\nR = 1...,from scipy.integrate import solve_ivp\n\nR = 1...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,0.0,exec_error,exec_error,exec_error,0.0
23,23,A cup of coffee at 90 ° C is left in a room at...,Let T(t) be the temperature. T(t) = 20 + 70e...,5.850000e+01,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import odeint\...,from scipy.integrate import odeint\nimport num...,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,55.7143,55.7143,55.7143,55.7143,exec_error,55.7154
24,24,A radioactive substance decays at a rate propo...,"A(t) = A0e^(-kt), 60 = 100e^(-10k) → e^(-10k...",1.360000e+01,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,To solve the problem of finding the half-life ...,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,13.5692,exec_error,13.5692,exec_error,exec_error
25,25,A 10mH inductor and a 20Ω resistor are connect...,KVL: L dI/dt + RI = V → dI/dt + 2000I = 10000...,5.000000e+00,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\n\nL = 1...,from scipy.integrate import solve_ivp\n\nL = 0...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,4.9981,exec_error,exec_error,4.9981
26,26,A cake is taken out of the oven at 350°F and p...,"T(t) = 70 + 280e^(-kt), T(10) = 300 → 230 = ...",2.573000e+02,```python\nimport numpy as np\nfrom scipy.inte...,is dT/dt = -k(T - T_env)\nHere T_env = 60°C (c...,from scipy.integrate import odeint\nimport num...,from scipy.integrate import odeint\nfrom scipy...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,258.9286,exec_error,258.9286,exec_error,exec_error,258.9287
27,27,"In 2020, an amount of 200,000 dollars was inv...","We have, dP/dt = -kP, where k = 0.10. Separa...",7.358000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,To solve the problem of determining the value ...,from scipy.integrate import solve_ivp\n\ndef m...,from scipy.integrate import solve_ivp\n\ndef m...,```python\nfrom scipy.integrate import solve_i...,73598.5698,73598.5698,exec_error,73598.5698,73598.5698,73598.5698
28,28,A bacterial culture doubles every 30 minutes. ...,"P(t) = 100e^(kt), P(30) = 200 → k = ln2/30 ≈ ...",6.400000e+03,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\n\ndef m...,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,6399.6471,6399.8082,6399.6471,6399.8152,exec_error,6399.6
29,29,A radioactive sample has a half-life of 12 day...,"A(t) = A0e^(-kt), 1/2 = e^(-12k) → k = ln2/12...",3.990000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,To solve the problem of determining how long i...,from scipy.integrate import solve_ivp\nimport ...,```\nimport numpy as np\nfrom scipy.integrate ...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,100.0,exec_error,exec_error
30,30,A tank contains 100 gallons of water. In erro...,Let x represent the number of pounds of salt i...,1.350000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,To solve the problem of determining how long i...,Here's the Python code that solves the problem...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,13.5137
31,31,An amount of 1 dollar is invested at 4 percen...,We are given the continuous compounding formul...,1.733000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,17.3287,exec_error,exec_error,exec_error,exec_error,17.3288
32,32,A body whose temperature is 180° is immersed i...,"Using Newton's Law of Cooling, we have the for...",2.000000e+00,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,To solve the problem of determining how long i...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
33,33,The temperature in a room is initially 70°. A ...,"Using Newton’s Law of Cooling, with T(0) = 7...",5.000000e+01,```python\nimport numpy as np\nfrom scipy.inte...,```python\nimport numpy as np\nfrom scipy.inte...,"To solve the problem, we use Newton's Law of C...",```python\nimport numpy as np\nfrom scipy.inte...,import numpy as np\nfrom scipy.integrate impor...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,50.0,exec_error
34,34,The rate at which radioactive nuclei decay is ...,We have N(t) = N0 e^(-kt) We know that half o...,1.250000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,12.5145,exec_error,4.9868,exec_error,12.5145
35,35,The population of Huambo town increases at a...,We have the population growth given by dP/dt =...,4.082400e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import solve_ivp\nimport ...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,40833.336,40833.336,exec_error,exec_error,40833.336
36,36,"An investment of 1,000,000 kwanzas loses value...",The continuous decay rate is described by the ...,2.800000e+01,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import solve_ivp\nfrom sc...,from scipy.integrate import solve_ivp\nfrom sc...,from scipy.integrate import solve_ivp\nfrom sc...,```python\nimport numpy as np\nfrom scipy.inte...,27.0268,exec_error,exec_error,exec_error,exec_error,exec_error
37,37,A man with a parachute jumps at a great height...,"We are given: W = 160lb, 0 ≤ t < 10, g = 32ft...",1.601000e+01,```python\nimport numpy as np\nfrom scipy.inte...,```python\nfrom scipy.integrate import solve_i...,from scipy.integrate import odeint\nimport num...,Here's the Python code that solves the problem...,from scipy.integrate import solve_ivp\n\ng = 3...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,exec_error,exec_error,exec_error,exec_error,16.0085
38,38,Find rate of interest per year compounded con...,Let: A(t): amount at time t A(0) = 10...,5.493000e+00,```python\nfrom scipy.integrate import solve_i...,```python\nimport numpy as np\nfrom scipy.opti...,To determine the continuous compounding intere...,from scipy.optimize import root_scalar\nimport...,from scipy.integrate import odeint\nfrom scipy...,```python\nimport numpy as np\nfrom scipy.inte...,0.0549,0.0549,exec_error,0.0549,exec_error,exec_error
39,39,The rate at which a certain substance dissolve...,The rate at which a certain substance dissolve...,7.140000e+00,```python\nfrom scipy.integrate import solve_i...,```python\nfrom scipy.integrate import solve_i...,NaN,from scipy.integrate import solve_ivp\nimport ...,from scipy.integrate import odeint\nimport num...,```python\nimport numpy as np\nfrom scipy.inte...,exec_error,4.1257,no_code,-2.7037,exec_error,exec_error

In [ ]:
df.drop([

    'Proposed Solution',
    'mistralai/mistral-small-3.2-24b-instruct:free_class',
    'deepseek/deepseek-r1-distill-llama-70b:free_class',
    'google/gemma-3-27b-it:free_class',
    'meta-llama/llama-3.1-405b-instruct:free_class',
    'x-ai/grok-3-mini-beta_class',
    'google/gemini-2.5-pro-preview_class'
], axis=1, inplace=True)

In [ ]:
df

,Index,Question,Answer,meta-llama/llama-3.1-405b-instruct:free_exec_result,google/gemma-3-27b-it:free_exec_result,deepseek/deepseek-r1-distill-llama-70b:free_exec_result,mistralai/mistral-small-3.2-24b-instruct:free_exec_result,x-ai/grok-3-mini-beta_exec_result,google/gemini-2.5-pro-preview_exec_result
0,0,A population of protozoa grows at a constant r...,2.350000e+02,234.9685,exec_error,234.9685,234.9685,234.9685,234.9685
1,1,A tank contains 1000 L of salt water with 15 k...,1.230000e+01,12.281,12.281,15.0,12.281,12.281,12.281
2,2,A resistor R=10Ω and an inductor L=2H are conn...,0.000000e+00,exec_error,exec_error,exec_error,exec_error,0.0,exec_error
3,3,A 5μF capacitor is charged through a 10kΩ resi...,5.490000e-02,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
4,4,An object is removed from an oven at 200°C and...,1.141900e+02,114.2857,210.0942,114.2857,114.2857,exec_error,114.2886
5,5,A certain village in Angola had a population ...,9.260000e+00,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
6,6,"Find the charge when t=0,2, in a series RC cir...",-5.290000e-02,10.0,exec_error,-132.7955,exec_error,exec_error,-0.0534
7,7,A resistor R=12Ω and an inductor L=4H are conn...,2.660000e-01,exec_error,0.2662,exec_error,0.2662,0.2662,0.2662
8,8,A roast chicken is removed from the oven when ...,1.364000e+02,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
9,9,"Escherichia coli, a common bacteria found in t...",1.676300e+02,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
10,10,"Suppose an amount of 100,000 kwanzas is invest...",1.730000e+01,27.4653,exec_error,exec_error,exec_error,exec_error,exec_error
11,11,"At time t = 0, a tank contains 4 lb of salt di...",8.110000e+01,81.1196,81.1196,exec_error,81.1196,81.12,81.1196
12,12,A bacterial culture grows at a rate proportion...,1.558800e+04,15588.5321,15589.011,15588.5321,exec_error,exec_error,15589.0
13,13,A tank contains 500L of brine with 25kg salt. ...,1.853000e+01,18.5205,18.5205,18.5205,18.5205,18.5205,18.5205
14,14,A hot metal cools from 300°F to 250°F in 10 mi...,1.944100e+02,156.2793,exec_error,156.2793,156.2793,exec_error,156.2808
15,15,A pizza cools from 400°F to 350°F in 5 minutes...,2.937300e+02,446.4701,241.6022,241.6072,241.6022,exec_error,241.6072
16,16,"An amount of 50,000 dollar is invested at 5 p...",2.197000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,21.971
17,17,A tank contains 100L of water with 5kg salt. B...,2.814000e+01,exec_error,19.5226,exec_error,19.5108,19.5108,19.5108
18,18,A population of insects decreases at a rate pr...,1.550000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
19,19,A tank contains 200 liters of salt water with ...,9.130000e+01,97.0696,97.0696,97.0696,97.0696,97.0696,97.0696
20,20,A resistor R=5Ω and an inductor L=1H are conne...,0.000000e+00,exec_error,0.0,exec_error,exec_error,0.0,0.0
21,21,A population of insects decreases at a rate pr...,1.550000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
22,22,"In an RC circuit with R = 10kΩ and C = 2μ F , ...",2.398000e-05,exec_error,0.0,exec_error,exec_error,exec_error,0.0
23,23,A cup of coffee at 90 ° C is left in a room at...,5.850000e+01,55.7143,55.7143,55.7143,55.7143,exec_error,55.7154
24,24,A radioactive substance decays at a rate propo...,1.360000e+01,exec_error,13.5692,exec_error,13.5692,exec_error,exec_error
25,25,A 10mH inductor and a 20Ω resistor are connect...,5.000000e+00,exec_error,exec_error,4.9981,exec_error,exec_error,4.9981
26,26,A cake is taken out of the oven at 350°F and p...,2.573000e+02,258.9286,exec_error,258.9286,exec_error,exec_error,258.9287
27,27,"In 2020, an amount of 200,000 dollars was inv...",7.358000e+01,73598.5698,73598.5698,exec_error,73598.5698,73598.5698,73598.5698
28,28,A bacterial culture doubles every 30 minutes. ...,6.400000e+03,6399.6471,6399.8082,6399.6471,6399.8152,exec_error,6399.6
29,29,A radioactive sample has a half-life of 12 day...,3.990000e+01,exec_error,exec_error,exec_error,100.0,exec_error,exec_error
30,30,A tank contains 100 gallons of water. In erro...,1.350000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,13.5137
31,31,An amount of 1 dollar is invested at 4 percen...,1.733000e+01,17.3287,exec_error,exec_error,exec_error,exec_error,17.3288
32,32,A body whose temperature is 180° is immersed i...,2.000000e+00,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
33,33,The temperature in a room is initially 70°. A ...,5.000000e+01,exec_error,exec_error,exec_error,exec_error,50.0,exec_error
34,34,The rate at which radioactive nuclei decay is ...,1.250000e+01,exec_error,12.5145,exec_error,4.9868,exec_error,12.5145
35,35,The population of Huambo town increases at a...,4.082400e+01,exec_error,40833.336,40833.336,exec_error,exec_error,40833.336
36,36,"An investment of 1,000,000 kwanzas loses value...",2.800000e+01,27.0268,exec_error,exec_error,exec_error,exec_error,exec_error
37,37,A man with a parachute jumps at a great height...,1.601000e+01,exec_error,exec_error,exec_error,exec_error,exec_error,16.0085
38,38,Find rate of interest per year compounded con...,5.493000e+00,0.0549,0.0549,exec_error,0.0549,exec_error,exec_error
39,39,The rate at which a certain substance dissolve...,7.140000e+00,exec_error,4.1257,no_code,-2.7037,exec_error,exec_error
40,40,A 12 volt battery is connected to a series cir...,1.200000e+00,exec_error,1.1996,exec_error,1.1996,1.1996,1.1996
41,41,The population of Ussinda Katota village of Tc...,2.668200e+04,60000.01,exec_error,26666.6667,exec_error,exec_error,26670.0
42,42,The air in a room whose volume is 10000 cubic ...,7.230000e-02,exec_error,0.0723,exec_error,0.0723,0.0723,0.0723
43,43,A body weighing 8 lb falls from rest toward th...,4.000000e+00,exec_error,14.7777,3.9992,15.9954,3.9992,3.9992
44,44,A sponge dries in an open air at a rate that i...,1.297000e+02,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
45,45,A 3μF capacitor is charged through a 15kΩ resi...,1.295000e-02,exec_error,exec_error,exec_error,exec_error,exec_error,exec_error
46,46,A wooden block weighing 50 lb is released from...,1.966080e+01,exec_error,19.7824,exec_error,19.7824,exec_error,19.7824
47,47,A boat is being towed at the rate of 18 ft/se...,1.162700e+01,exec_error,17.3192,exec_error,exec_error,17.3192,11.6284
48,48,An object on a sled is pulled by a force of 10...,4.970000e+00,exec_error,0.7233,4.9657,4.9667,4.9657,4.9657
49,49,"In 2024, an investment of 15,000,000 kwanzas w...",9.097500e+06,9097965.0561,9097965.0561,9098000.0,9097965.0561,9097965.0561,9097965.0561

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import sklearn

print(f"🔍 Versão do scikit-learn: {sklearn.__version__}")

ABS_TOL = 0.1
REL_TOL = 0.05

df = df  # Substitua pelo caminho correto
answer_col = "Answer"
model_cols = [col for col in df.columns if col.endswith('_exec_result')]

metrics = []

for model in model_cols:
    y_true = []
    y_pred = []
    acc_count = 0
    total = 0

    for truth, pred in zip(df[answer_col], df[model]):
        total += 1
        if isinstance(pred, str) and "exec_error" in pred:
            continue
        try:
            pred = float(pred)
            truth = float(truth)
        except:
            continue

        y_true.append(truth)
        y_pred.append(pred)

        if abs(pred - truth) <= ABS_TOL or abs(pred - truth) / max(abs(truth), 1e-8) <= REL_TOL:
            acc_count += 1

    if len(y_true) == 0:
        metrics.append({
            "model": model,
            "accuracy (%)": 0.0 if total > 0 else None,
            "mae (%)": None,
            "mse (%)": None,
            "rmse (%)": None,
            "r2 (%)": None,


        })
        continue

    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    metrics.append({
        "model": model,
        "accuracy (%)": round((acc_count / total) * 100,1),
        "mae (%)": round(mae * 100,1),
        "mse (%)": round(mse * 100,1),
        "rmse (%)": round(rmse * 100,1),
        "r2 (%)": round(r2 * 100,1 ),


    })

metrics_df = pd.DataFrame(metrics)
metrics_df = metrics_df.sort_values(by="accuracy (%)", ascending=False)

print("📊 Métricas de avaliação por modelo (em %):")
print(metrics_df.to_string(index=False))

🔍 Versão do scikit-learn: 1.6.1
📊 Métricas de avaliação por modelo (em %):
                                                    model  accuracy (%)  mae (%)      mse (%)  rmse (%)  r2 (%)
                google/gemini-2.5-pro-preview_exec_result          54.0 348198.1 2.142477e+10 1463720.2   100.0
                   google/gemma-3-27b-it:free_exec_result          30.0 442224.4 2.719301e+10 1649030.2   100.0
mistralai/mistral-small-3.2-24b-instruct:free_exec_result          28.0 309137.1 2.252562e+10 1500853.7   100.0
                        x-ai/grok-3-mini-beta_exec_result          26.0 435354.3 3.180083e+10 1783278.6   100.0
      meta-llama/llama-3.1-405b-instruct:free_exec_result          24.0 537684.0 3.258128e+10 1805028.4   100.0
  deepseek/deepseek-r1-distill-llama-70b:free_exec_result          24.0 230804.2 9.246117e+09  961567.3   100.0